/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school.management.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author RK Anik
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    int xx ; int xy ;
    public DashBoard() {
        initComponents();
        refresh();
    }
    static Connection conn = null ;
    PreparedStatement pst = null ;
    ResultSet rs = null ;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroud = new javax.swing.JPanel();
        Middle = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        totalteachers = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        totalother = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        totalstudents = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Updater1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Results = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        markupdate = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        DeleteInfo = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Subjects = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        TeacherSheduler = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        TList = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        promote = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Updater = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Workerinfo = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        minimize = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        school = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Sidebar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Payment = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Dashboard = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Admission = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        Studentinfo = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Teacherinfo = new javax.swing.JButton();
        copyright = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        setLocation(new java.awt.Point(250, 70));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        Middle.setBackground(new java.awt.Color(255, 255, 255));
        Middle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(49, 62, 68));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/total teachers.png"))); // NOI18N
        jLabel10.setText("Total Teachers");
        jPanel13.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 40));

        totalteachers.setEditable(false);
        totalteachers.setBackground(new java.awt.Color(49, 62, 68));
        totalteachers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalteachers.setForeground(new java.awt.Color(204, 204, 204));
        totalteachers.setBorder(null);
        totalteachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalteachersActionPerformed(evt);
            }
        });
        jPanel13.add(totalteachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 57, 48, 30));

        Middle.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 190, 100));

        jPanel10.setBackground(new java.awt.Color(49, 62, 68));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/total employee.png"))); // NOI18N
        jLabel5.setText("Others");
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 128, 40));

        totalother.setEditable(false);
        totalother.setBackground(new java.awt.Color(49, 62, 68));
        totalother.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalother.setForeground(new java.awt.Color(204, 204, 204));
        totalother.setBorder(null);
        totalother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalotherActionPerformed(evt);
            }
        });
        jPanel10.add(totalother, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 57, 48, 30));

        Middle.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 150, 100));

        jPanel11.setBackground(new java.awt.Color(49, 62, 68));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalstudents.setEditable(false);
        totalstudents.setBackground(new java.awt.Color(49, 62, 68));
        totalstudents.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalstudents.setForeground(new java.awt.Color(204, 204, 204));
        totalstudents.setBorder(null);
        totalstudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalstudentsActionPerformed(evt);
            }
        });
        jPanel11.add(totalstudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 57, 48, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/total students.png"))); // NOI18N
        jLabel6.setText("Total Students");
        jPanel11.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 40));

        Middle.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 100));

        jPanel1.setBackground(new java.awt.Color(49, 62, 68));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Updater1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Updater1.setForeground(new java.awt.Color(255, 255, 255));
        Updater1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lists.png"))); // NOI18N
        Updater1.setBorder(null);
        Updater1.setContentAreaFilled(false);
        Updater1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Updater1ActionPerformed(evt);
            }
        });
        jPanel1.add(Updater1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 5, 70, 70));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Delete Info");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 100, -1));

        Results.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Admission_1.png"))); // NOI18N
        Results.setContentAreaFilled(false);
        Results.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultsActionPerformed(evt);
            }
        });
        jPanel1.add(Results, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 70, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Results");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 70, -1));

        markupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/markupdate.png"))); // NOI18N
        markupdate.setContentAreaFilled(false);
        markupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markupdateActionPerformed(evt);
            }
        });
        jPanel1.add(markupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 70, 60));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Student List");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, -1));

        DeleteInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        DeleteInfo.setContentAreaFilled(false);
        DeleteInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteInfoActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 60, 60));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Mark Upload");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 90, -1));

        Subjects.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/subjects.png"))); // NOI18N
        Subjects.setContentAreaFilled(false);
        Subjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectsActionPerformed(evt);
            }
        });
        jPanel1.add(Subjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 60, 60));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Subjects");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 100, -1));

        TeacherSheduler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teacher shedule.png"))); // NOI18N
        TeacherSheduler.setContentAreaFilled(false);
        TeacherSheduler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherShedulerActionPerformed(evt);
            }
        });
        jPanel1.add(TeacherSheduler, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 60, 60));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Teacher Sheduler");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 120, -1));

        TList.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TList.setForeground(new java.awt.Color(255, 255, 255));
        TList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tlist.png"))); // NOI18N
        TList.setBorder(null);
        TList.setContentAreaFilled(false);
        TList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TListActionPerformed(evt);
            }
        });
        jPanel1.add(TList, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, 60));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Teacher List");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 90, -1));

        promote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/promote.png"))); // NOI18N
        promote.setContentAreaFilled(false);
        promote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promoteActionPerformed(evt);
            }
        });
        jPanel1.add(promote, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 90, 60));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Promote Student");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 90, -1));

        Middle.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 690, 90));

        jPanel3.setBackground(new java.awt.Color(49, 62, 68));

        Updater.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Updater.setForeground(new java.awt.Color(255, 255, 255));
        Updater.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/info updater.png"))); // NOI18N
        Updater.setBorder(null);
        Updater.setContentAreaFilled(false);
        Updater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdaterActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Info Update");

        Workerinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Worker.png"))); // NOI18N
        Workerinfo.setContentAreaFilled(false);
        Workerinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkerinfoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Worker's Info");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Updater, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Workerinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(Workerinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Updater, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        Middle.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 90, 360));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboardpic.jpg"))); // NOI18N
        Middle.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        Header.setBackground(new java.awt.Color(9, 144, 144));
        Header.setForeground(new java.awt.Color(0, 153, 153));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimize.setBorder(null);
        minimize.setContentAreaFilled(false);
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        Header.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 30, 30));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        close.setBorder(null);
        close.setContentAreaFilled(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        Header.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 30, 30));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("R.A.N.T.R.M. High School");
        Header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 390, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(225, 225, 225));
        jLabel7.setText("Maznabari, Kumariyabari, Kazipur, Sirajganj");
        Header.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 270, -1));

        school.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/school.png"))); // NOI18N
        Header.add(school, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 110, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(225, 225, 225));
        jLabel1.setText("Placed: 1986        Reg. No. : 9874561");
        Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 220, -1));

        jLabel9.setForeground(new java.awt.Color(225, 225, 225));
        jLabel9.setText("Email: rantrm@gmail.com   Contact : +8801703577953 , +8801987886450");
        Header.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 430, 20));

        Sidebar.setBackground(new java.awt.Color(49, 62, 68));
        Sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(66, 169, 86));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Payment.setBackground(new java.awt.Color(0, 102, 102));
        Payment.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Payment.setForeground(new java.awt.Color(255, 255, 255));
        Payment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/payment.png"))); // NOI18N
        Payment.setText("Salary");
        Payment.setBorderPainted(false);
        Payment.setContentAreaFilled(false);
        Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentActionPerformed(evt);
            }
        });
        jPanel2.add(Payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 60));

        Sidebar.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 170, 60));

        jPanel5.setBackground(new java.awt.Color(72, 135, 242));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard.setBackground(new java.awt.Color(0, 102, 102));
        Dashboard.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N
        Dashboard.setText("Dashboard");
        Dashboard.setBorderPainted(false);
        Dashboard.setContentAreaFilled(false);
        Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardActionPerformed(evt);
            }
        });
        jPanel5.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        Sidebar.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 60));

        jPanel6.setBackground(new java.awt.Color(228, 58, 57));
        jPanel6.setPreferredSize(new java.awt.Dimension(170, 60));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admission.setBackground(new java.awt.Color(0, 102, 102));
        Admission.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Admission.setForeground(new java.awt.Color(255, 255, 255));
        Admission.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Admission.png"))); // NOI18N
        Admission.setText("Admission");
        Admission.setBorderPainted(false);
        Admission.setContentAreaFilled(false);
        Admission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmissionActionPerformed(evt);
            }
        });
        jPanel6.add(Admission, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        Sidebar.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 170, 60));

        jPanel7.setBackground(new java.awt.Color(248, 187, 40));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Studentinfo.setBackground(new java.awt.Color(18, 83, 83));
        Studentinfo.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Studentinfo.setForeground(new java.awt.Color(255, 255, 255));
        Studentinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/student info.png"))); // NOI18N
        Studentinfo.setText("Student's Info");
        Studentinfo.setBorderPainted(false);
        Studentinfo.setContentAreaFilled(false);
        Studentinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentinfoActionPerformed(evt);
            }
        });
        jPanel7.add(Studentinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        Sidebar.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, 60));

        jPanel8.setBackground(new java.awt.Color(72, 135, 242));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Teacherinfo.setBackground(new java.awt.Color(0, 102, 102));
        Teacherinfo.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Teacherinfo.setForeground(new java.awt.Color(255, 255, 255));
        Teacherinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teacher info.png"))); // NOI18N
        Teacherinfo.setText("Teacher's Info");
        Teacherinfo.setBorderPainted(false);
        Teacherinfo.setContentAreaFilled(false);
        Teacherinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherinfoActionPerformed(evt);
            }
        });
        jPanel8.add(Teacherinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 180, 60));

        Sidebar.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 170, 60));

        copyright.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        copyright.setForeground(new java.awt.Color(153, 153, 153));
        copyright.setText("All Rights Reserved © Kochi lnc. 2018");
        Sidebar.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 433, 210, 30));

        jPanel12.setBackground(new java.awt.Color(255, 51, 51));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logout.setText("Log Out");
        logout.setBorder(null);
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel12.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 60));

        Sidebar.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 170, 60));

        javax.swing.GroupLayout backgroudLayout = new javax.swing.GroupLayout(backgroud);
        backgroud.setLayout(backgroudLayout);
        backgroudLayout.setHorizontalGroup(
            backgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroudLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(Middle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        backgroudLayout.setVerticalGroup(
            backgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(backgroudLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(backgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Middle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(backgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 552));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void refresh(){
        try{
            conn = DatabaseConnection.ConnectDB();
            String query = "select Count( distinct Student_Id) as Total_Student from StudentAccademicInfo";
            String query2 = "select Count(Teacher_Id) as Total_Teacher from TeacherPersonalInfo";
            String query3 = "select Count(Worker_Id) as Total_Others from WorkerPersonalInfo";
            pst = conn.prepareStatement(query);
            PreparedStatement pst2 = conn.prepareStatement(query2);
            PreparedStatement pst3 = conn.prepareStatement(query3);
            rs = pst.executeQuery();
            ResultSet rs2 = pst2.executeQuery();
            ResultSet rs3 = pst3.executeQuery();
            if( rs.next() ){
                totalstudents.setText( rs.getString("Total_Student"));
            }
            if( rs2.next() ){
                totalteachers.setText( rs2.getString("Total_Teacher"));
            }
            if( rs3.next() ){
                totalother.setText( rs3.getString("Total_Others"));
            }
        }catch( ClassNotFoundException | SQLException e ){JOptionPane.showMessageDialog(null, e);}
    }
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        dispose();
        SMS_Login login = new SMS_Login();
        login.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void TeacherinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherinfoActionPerformed
        dispose();
        Teachers_Info teacher = new Teachers_Info();
        teacher.setVisible(true);
    }//GEN-LAST:event_TeacherinfoActionPerformed

    private void StudentinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentinfoActionPerformed
        dispose();
        Students_Info finder = new Students_Info();
        finder.setVisible(true);
    }//GEN-LAST:event_StudentinfoActionPerformed

    private void AdmissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmissionActionPerformed
        dispose();
        Admission admission = new Admission();
        admission.setVisible(true);
    }//GEN-LAST:event_AdmissionActionPerformed

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardActionPerformed

    private void PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentActionPerformed
        dispose();
        Salary salary = new Salary();
        salary.setVisible(true);
    }//GEN-LAST:event_PaymentActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void totalstudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalstudentsActionPerformed
        
    }//GEN-LAST:event_totalstudentsActionPerformed

    private void totalotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalotherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalotherActionPerformed

    private void totalteachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalteachersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalteachersActionPerformed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx , y - xy );
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void UpdaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdaterActionPerformed
        dispose();
        UpdaterLink update = new UpdaterLink();
        update.setVisible(true);
    }//GEN-LAST:event_UpdaterActionPerformed

    private void Updater1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Updater1ActionPerformed
        dispose();
        Students_List list = new Students_List();
        list.setVisible(true);
    }//GEN-LAST:event_Updater1ActionPerformed

    private void ResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultsActionPerformed
        dispose();
        AccademicResults results = new AccademicResults();
        results.setVisible(true);
    }//GEN-LAST:event_ResultsActionPerformed

    private void markupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markupdateActionPerformed
        dispose();
        UploadMark markup = new UploadMark();
        markup.setVisible(true);
    }//GEN-LAST:event_markupdateActionPerformed

    private void DeleteInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteInfoActionPerformed
        dispose();
        DeleteInfo del = new DeleteInfo();
        del.setVisible(true);
    }//GEN-LAST:event_DeleteInfoActionPerformed

    private void SubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectsActionPerformed
        dispose();
        Subjects sub = new Subjects();
        sub.setVisible(true);
        
    }//GEN-LAST:event_SubjectsActionPerformed

    private void TeacherShedulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherShedulerActionPerformed
        dispose();
        Teacher_Schedule shedule = new Teacher_Schedule();
        shedule.setVisible(true);
    }//GEN-LAST:event_TeacherShedulerActionPerformed

    private void WorkerinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkerinfoActionPerformed
        dispose();
        Worker_Info wi = new Worker_Info();
        wi.setVisible(true);
    }//GEN-LAST:event_WorkerinfoActionPerformed

    private void TListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TListActionPerformed
        dispose();
        TeacherList tlist = new TeacherList();
        tlist.setVisible(true);
    }//GEN-LAST:event_TListActionPerformed

    private void promoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promoteActionPerformed
        dispose();
        PromoteStudent prom = new PromoteStudent();
        prom.setVisible(true);
    }//GEN-LAST:event_promoteActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admission;
    private javax.swing.JButton Dashboard;
    private javax.swing.JButton DeleteInfo;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Middle;
    private javax.swing.JButton Payment;
    private javax.swing.JButton Results;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JButton Studentinfo;
    private javax.swing.JButton Subjects;
    private javax.swing.JButton TList;
    private javax.swing.JButton TeacherSheduler;
    private javax.swing.JButton Teacherinfo;
    private javax.swing.JButton Updater;
    private javax.swing.JButton Updater1;
    private javax.swing.JButton Workerinfo;
    private javax.swing.JPanel backgroud;
    private javax.swing.JButton close;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton logout;
    private javax.swing.JButton markupdate;
    private javax.swing.JButton minimize;
    private javax.swing.JButton promote;
    private javax.swing.JLabel school;
    private javax.swing.JTextField totalother;
    private javax.swing.JTextField totalstudents;
    private javax.swing.JTextField totalteachers;
    // End of variables declaration//GEN-END:variables
}
