/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school.management.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author RK Anik
 */
public class PromoteStudent extends javax.swing.JFrame {

    /**
     * Creates new form PromoteStudent
     */
    public PromoteStudent() {
        initComponents();
        Dept.setEnabled(false);
    }
    Connection conn = null;
    PreparedStatement pst = null ;
    ResultSet rs = null ;
    int xx,xy;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        close = new javax.swing.JButton();
        minimize = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Shadow = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        Promote = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        Passed = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Failed = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Show = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Year = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Dept = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Sclass = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        PF = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 70));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        jPanel2.setBackground(new java.awt.Color(54, 71, 75));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        close.setContentAreaFilled(false);
        close.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeMouseMoved(evt);
            }
        });
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel3.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 40, 30));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimize.setContentAreaFilled(false);
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        jPanel3.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 30, 30));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel3.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Promote Students");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 550, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 40));

        Shadow.setBackground(new java.awt.Color(0, 123, 123));
        Shadow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(Shadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 990, 10));

        RTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Section", "GPA", "Grade", "Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RTable.setGridColor(new java.awt.Color(255, 255, 255));
        RTable.setRowHeight(32);
        jScrollPane1.setViewportView(RTable);
        if (RTable.getColumnModel().getColumnCount() > 0) {
            RTable.getColumnModel().getColumn(0).setResizable(false);
            RTable.getColumnModel().getColumn(1).setResizable(false);
            RTable.getColumnModel().getColumn(2).setResizable(false);
            RTable.getColumnModel().getColumn(3).setResizable(false);
            RTable.getColumnModel().getColumn(4).setResizable(false);
            RTable.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 570, 290));

        jPanel4.setBackground(new java.awt.Color(67, 82, 86));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Promote.setBackground(new java.awt.Color(0, 153, 153));
        Promote.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Promote.setForeground(new java.awt.Color(255, 255, 255));
        Promote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Promote.setText("Promote to Next Class");
        Promote.setOpaque(true);
        Promote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PromoteMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PromoteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PromoteMouseReleased(evt);
            }
        });
        jPanel4.add(Promote, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 340, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Total Student");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 340, 30));

        Total.setEditable(false);
        Total.setBackground(new java.awt.Color(79, 94, 97));
        Total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 255, 255));
        Total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Total.setBorder(null);
        jPanel4.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 340, 40));

        Passed.setEditable(false);
        Passed.setBackground(new java.awt.Color(79, 94, 97));
        Passed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Passed.setForeground(new java.awt.Color(255, 255, 255));
        Passed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Passed.setBorder(null);
        jPanel4.add(Passed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 340, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total Passed");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 340, 30));

        Failed.setEditable(false);
        Failed.setBackground(new java.awt.Color(79, 94, 97));
        Failed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Failed.setForeground(new java.awt.Color(255, 255, 255));
        Failed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Failed.setBorder(null);
        jPanel4.add(Failed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 340, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Total Total Failed");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 340, 30));

        Show.setBackground(new java.awt.Color(0, 153, 153));
        Show.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Show.setForeground(new java.awt.Color(255, 255, 255));
        Show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Show.setText("Show");
        Show.setOpaque(true);
        Show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ShowMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ShowMouseReleased(evt);
            }
        });
        jPanel4.add(Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 340, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 360, 460));

        jPanel5.setBackground(new java.awt.Color(67, 82, 86));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Year.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "2014", "2015", "2016", "2017", "2018", "2019" }));
        jPanel5.add(Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Year");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 80, 30));

        Dept.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Science", "Commerce", "Arts" }));
        jPanel5.add(Dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 170, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Department");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 110, 30));

        Sclass.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Sclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine" }));
        Sclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SclassActionPerformed(evt);
            }
        });
        jPanel5.add(Sclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Class");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 570, 90));

        PF.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        PF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Passed", "Failed" }));
        jPanel2.add(PF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 290, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Please Select");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 150, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseMoved

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered

    }//GEN-LAST:event_closeMouseEntered

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        DashBoard back = new DashBoard();
        back.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation( x - xx , y - xy );
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void SclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SclassActionPerformed
        int a = Sclass.getSelectedIndex();
        if( a == 9 || a == 10 ){
            Dept.setEnabled(true);
        }
        else{
        Dept.setEnabled(false);}
    }//GEN-LAST:event_SclassActionPerformed

    private void ShowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMousePressed
        Show.setBackground(new java.awt.Color(0,122,122));
    }//GEN-LAST:event_ShowMousePressed

    private void ShowMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseReleased
        Show.setBackground(new java.awt.Color(0,153,153));
    }//GEN-LAST:event_ShowMouseReleased

    private void PromoteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PromoteMousePressed
        Promote.setBackground(new java.awt.Color(0,122,122));
    }//GEN-LAST:event_PromoteMousePressed

    private void PromoteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PromoteMouseReleased
        Promote.setBackground(new java.awt.Color(0,153,153));
    }//GEN-LAST:event_PromoteMouseReleased

    private void ShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseClicked
        
        try{
            conn = DatabaseConnection.ConnectDB();
            if( Sclass.getSelectedIndex() == 0  || Year.getSelectedIndex() == 0 || PF.getSelectedIndex() == 0){
                JOptionPane.showMessageDialog(null,"Please Fill-Up all the fields");
            }else{
                String q15 = "delete from Temp";
                PreparedStatement pst15 = conn.prepareStatement(q15);
                pst15.execute();
                
                int Scls = 0 ;
                String q3 = "Select Class_Id from Class where Class_Name = '"+Sclass.getSelectedItem()+"'";
                PreparedStatement pst2 = conn.prepareStatement(q3);
                ResultSet rs2 = pst2.executeQuery();
                if( rs2.next() ){
                    Scls = rs2.getInt("Class_Id");
                }
                int Y = 0 ;
                String q5 = "select Year_Id from Year where Year = '"+Year.getSelectedItem()+"'";
                PreparedStatement pst5 = conn.prepareStatement(q5);
                ResultSet rs5 = pst5.executeQuery();
                if( rs5.next() ){
                    Y = rs5.getInt("Year_Id");
                }
                
                q15 = "select count(Student_Id) as Total from StudentAccademicInfo\n" +
                    "where Class_Id = "+Scls+" and Year_Id = "+Y+";";
                pst15 = conn.prepareStatement(q15);
                ResultSet rs15 = pst15.executeQuery();
                if( rs15.next() ){Total.setText(rs15.getString("Total"));}
                pst15.close();rs15.close();
                
                String q = "insert into Fail\n" +
                    "select distinct student_id from Marks where Student_Id in\n" +
                    "(select distinct student_Id as fail from Marks m  inner join GradePoint gp on \n" +
                    "m.Grade_Id = gp.Grade_Id where  (Class_Id = "+Scls+" and  m.Grade_Id = 7 and Exam_Id = 3));";
                PreparedStatement pst = conn.prepareStatement(q);
                pst.execute();
                pst.close();
                
                q15 = "select count(Student_Id) as Total from Fail";
                pst15 = conn.prepareStatement(q15);
                rs15 = pst15.executeQuery();
                if( rs15.next() ){Failed.setText(rs15.getString("Total"));}
                pst15.close();rs15.close();
                
                int b =  0;b = PF.getSelectedIndex();
                
                if( b == 1 ){
                    String q10 = "insert into Pass\n" +
                        "select distinct m.student_id from marks m where Student_Id in \n" +
                        "(select m.Student_Id as pass from marks m left join Fail pf on"+
                        " m.Student_Id = pf.student_id where (m.Class_Id= "+Scls+" and pf.student_id is null));";
                    PreparedStatement pst10 = conn.prepareStatement(q10);
                    pst10.execute();
                    pst10.close();
                    
                    q15 = "select count(Student_Id) as Total from Pass";
                    pst15 = conn.prepareStatement(q15);
                    rs15 = pst15.executeQuery();
                    if( rs15.next() ){Passed.setText(rs15.getString("Total"));}
                    pst15.close();rs15.close();
                
                    String q2 = "select Student_Id from Pass";
                    PreparedStatement pst11 = conn.prepareStatement(q2);
                    ResultSet rs = pst11.executeQuery();
                    while ( rs.next() ){
                        String q4 = "select sai.Student_Id,Student_Name,Section_Name as Section,\n" +
                            "(SUM(gp.Grade_Point)/COUNT(mr.Subject_Id)) as GPA,Year\n" +
                            "from StudentAccademicInfo sai inner join StudentPersonalInfo spi\n" +
                            "on sai.Student_Id = spi.Student_Id inner join Section sc\n" +
                            "on sai.Section_Id = sc.Section_Id inner join Marks mr\n" +
                            "on sai.Student_Id = mr.Student_Id inner join GradePoint gp\n" +
                            "on mr.Grade_Id = gp.Grade_Id inner join Year y\n" +
                            "on mr.Year_Id = y.Year_Id where (sai.Student_Id='"+rs.getString("Student_Id")+"'\n" +
                           "and (sai.Class_Id = "+Scls+" and( Exam_Id = 3 and sai.Year_Id = "+Y+")))\n" +
                           "group by sai.Student_Id,Student_Name,Section_Name,y.Year;";
                      PreparedStatement pst4 = conn.prepareStatement(q4);
                      ResultSet rs4 = pst4.executeQuery();
                      if( rs4.next() ){
                          String q9 = "insert into Temp values('"+rs4.getString("Student_Id")+"','"+rs4.getString("Student_Name")+"',"+
                                "'"+rs4.getString("Section")+"','"+rs4.getDouble("GPA")+"','"+rs4.getInt("Year")+"')";
                            PreparedStatement pst9 = conn.prepareStatement(q9);
                            pst9.execute();
                       }
                   }
                   String q12 = "Select * from Temp";
                   PreparedStatement pst12 = conn.prepareStatement(q12);
                   ResultSet rs12 = pst12.executeQuery();
                   RTable.setModel(DbUtils.resultSetToTableModel(rs12));
                   String q13 = "delete from Pass";
                   String q14 = "delete from Fail";
                   PreparedStatement pst13 = conn.prepareStatement(q13);
                   pst13.execute();
                   pst13.close();
                   pst13 = conn.prepareStatement(q14);
                   pst13.execute();
                   pst13.close();
                }
                else if( b == 2 ){
                    String q2 = "select Student_Id from Fail";
                    PreparedStatement pst11 = conn.prepareStatement(q2);
                    ResultSet rs = pst11.executeQuery();
                    while ( rs.next() ){ 
                        String q4 = "select sai.Student_Id,Student_Name,Section_Name as Section,\n" +
                            "(SUM(gp.Grade_Point)/COUNT(mr.Subject_Id)) as GPA,Year\n" +
                            "from StudentAccademicInfo sai inner join StudentPersonalInfo spi\n" +
                            "on sai.Student_Id = spi.Student_Id inner join Section sc\n" +
                            "on sai.Section_Id = sc.Section_Id inner join Marks mr\n" +
                            "on sai.Student_Id = mr.Student_Id inner join GradePoint gp\n" +
                            "on mr.Grade_Id = gp.Grade_Id inner join Year y\n" +
                            "on mr.Year_Id = y.Year_Id where (sai.Student_Id='"+rs.getString("Student_Id")+"'\n" +
                           "and (sai.Class_Id = "+Scls+" and( Exam_Id = 3 and sai.Year_Id = "+Y+")))\n" +
                           "group by sai.Student_Id,Student_Name,Section_Name,y.Year;";
                      PreparedStatement pst4 = conn.prepareStatement(q4);
                      ResultSet rs4 = pst4.executeQuery();
                      if( rs4.next() ){
                          String q9 = "insert into Temp values('"+rs4.getString("Student_Id")+"','"+rs4.getString("Student_Name")+"',"+
                                "'"+rs4.getString("Section")+"','0.00','"+rs4.getInt("Year")+"')";
                            PreparedStatement pst9 = conn.prepareStatement(q9);
                            pst9.execute();
                       }
                   }
                   String q12 = "Select * from Temp";
                   PreparedStatement pst12 = conn.prepareStatement(q12);
                   ResultSet rs12 = pst12.executeQuery();
                   RTable.setModel(DbUtils.resultSetToTableModel(rs12));
                   String q13 = "delete from Pass";
                   String q14 = "delete from Fail";
                   PreparedStatement pst13 = conn.prepareStatement(q13);
                   pst13.execute();
                   pst13.close();
                   pst13 = conn.prepareStatement(q14);
                   pst13.execute();
                   pst13.close();
                }
            }
                
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
        
    }//GEN-LAST:event_ShowMouseClicked

    private void PromoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PromoteMouseClicked
        if( Sclass.getSelectedIndex() == 0  || Year.getSelectedIndex() == 0 || PF.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null,"Please Fill-Up all the fields\nAnd Then Click on SHOW");
        }else{
            try{
                conn = DatabaseConnection.ConnectDB();
                String sql = "delete from Temp";
                pst = conn.prepareStatement(sql);
                pst.execute();
                pst.close();
                
                int Scls = 0 ;
                sql = "Select Class_Id from Class where Class_Name = '"+Sclass.getSelectedItem()+"'";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                if( rs.next() ){
                    Scls = rs.getInt("Class_Id");
                }
                pst.close();rs.close();
                
                int Y = 0 ;
                sql = "select Year_Id from Year where Year = '"+Year.getSelectedItem()+"'";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                if( rs.next() ){
                    Y = rs.getInt("Year_Id");
                }
                pst.close();rs.close();
                
                sql = "insert into Fail\n" +
                    "select distinct student_id from Marks where Student_Id in\n" +
                    "(select distinct student_Id as fail from Marks m  inner join GradePoint gp on \n" +
                    "m.Grade_Id = gp.Grade_Id where  (Class_Id = "+Scls+" and  m.Grade_Id = 7 and Exam_Id = 3));";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                pst.close();
                
                sql = "insert into Pass\n" +
                        "select distinct m.student_id from marks m where Student_Id in \n" +
                        "(select m.Student_Id as pass from marks m left join Fail pf on"+
                        " m.Student_Id = pf.student_id where (m.Class_Id= "+Scls+" and pf.student_id is null));";
                pst = conn.prepareStatement(sql);
                pst.execute();
                pst.close();
                
                String q2 = "select Student_Id from Pass";
                PreparedStatement pst11 = conn.prepareStatement(q2);
                ResultSet rs = pst11.executeQuery();
                while ( rs.next() ){
                    String q4 = "select sai.Student_Id,Student_Name,Section_Name as Section,\n" +
                            "(SUM(gp.Grade_Point)/COUNT(mr.Subject_Id)) as GPA,Year\n" +
                            "from StudentAccademicInfo sai inner join StudentPersonalInfo spi\n" +
                            "on sai.Student_Id = spi.Student_Id inner join Section sc\n" +
                            "on sai.Section_Id = sc.Section_Id inner join Marks mr\n" +
                            "on sai.Student_Id = mr.Student_Id inner join GradePoint gp\n" +
                            "on mr.Grade_Id = gp.Grade_Id inner join Year y\n" +
                            "on mr.Year_Id = y.Year_Id where (sai.Student_Id='"+rs.getString("Student_Id")+"'\n" +
                           "and (sai.Class_Id = "+Scls+" and( Exam_Id = 3 and sai.Year_Id = "+Y+")))\n" +
                           "group by sai.Student_Id,Student_Name,Section_Name,y.Year;";
                    PreparedStatement pst4 = conn.prepareStatement(q4);
                    ResultSet rs4 = pst4.executeQuery();
                    if( rs4.next() ){
                        String q9 = "insert into Temp values('"+rs4.getString("Student_Id")+"','"+rs4.getString("Student_Name")+"',"+
                                "'"+rs4.getString("Section")+"','"+rs4.getDouble("GPA")+"','"+rs4.getInt("Year")+"')";
                        PreparedStatement pst9 = conn.prepareStatement(q9);
                        pst9.execute();
                       }
                   }
                
                   
                Scls++;Y++;
                
                sql = "insert into StudentAccademicInfo  \n" +
                    "select distinct sai.Student_Id, "+Scls+" Class_Id, Section_id,\n" +
                    "null class_roll,null Depertment_Name, "+Y+" Year_Id,\n" +
                    "null SSC_Roll_Number, null SSC_Registration_Number\n" +
                    "from temp t inner join StudentAccademicInfo sai on sai.Student_Id = t.Student_Id ;";
                pst = conn.prepareStatement(sql);
                pst.execute();
                pst.close();
                String q13 = "delete from Pass";
                   String q14 = "delete from Fail";
                   PreparedStatement pst13 = conn.prepareStatement(q13);
                   pst13.execute();
                   pst13.close();
                   pst13 = conn.prepareStatement(q14);
                   pst13.execute();
                   pst13.close();
                JOptionPane.showMessageDialog(null, "Students Succesfully Promoted");
                
            }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
        }
    }//GEN-LAST:event_PromoteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromoteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromoteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromoteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromoteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PromoteStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Dept;
    private javax.swing.JTextField Failed;
    private javax.swing.JComboBox<String> PF;
    private javax.swing.JTextField Passed;
    private javax.swing.JLabel Promote;
    private javax.swing.JTable RTable;
    private javax.swing.JComboBox<String> Sclass;
    private javax.swing.JPanel Shadow;
    private javax.swing.JLabel Show;
    private javax.swing.JTextField Total;
    private javax.swing.JComboBox<String> Year;
    private javax.swing.JButton back;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton minimize;
    // End of variables declaration//GEN-END:variables
}
