/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school.management.system;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author RK Anik
 */
public class Students_List extends javax.swing.JFrame {

    /**
     * Creates new form Students_List
     */
    
    int xx , xy , i , Idept ;
    Connection conn = null;
    PreparedStatement pst = null ;
    ResultSet rs = null ;
    public Students_List() {
        initComponents();
        section.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SList = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        close = new javax.swing.JButton();
        minimize = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Shadow = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cls = new javax.swing.JComboBox<>();
        Submit = new javax.swing.JLabel();
        Reset = new javax.swing.JLabel();
        dept = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        section = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(220, 100));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 123, 123)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Student Name", "Class", "Class Roll", "Section", "Department", "Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SList.setGridColor(new java.awt.Color(255, 255, 255));
        SList.setRowHeight(25);
        SList.setSelectionBackground(new java.awt.Color(0, 123, 123));
        jScrollPane1.setViewportView(SList);
        if (SList.getColumnModel().getColumnCount() > 0) {
            SList.getColumnModel().getColumn(0).setResizable(false);
            SList.getColumnModel().getColumn(0).setPreferredWidth(30);
            SList.getColumnModel().getColumn(1).setResizable(false);
            SList.getColumnModel().getColumn(1).setPreferredWidth(100);
            SList.getColumnModel().getColumn(2).setResizable(false);
            SList.getColumnModel().getColumn(2).setPreferredWidth(25);
            SList.getColumnModel().getColumn(3).setResizable(false);
            SList.getColumnModel().getColumn(4).setResizable(false);
            SList.getColumnModel().getColumn(4).setPreferredWidth(25);
            SList.getColumnModel().getColumn(5).setResizable(false);
            SList.getColumnModel().getColumn(6).setResizable(false);
            SList.getColumnModel().getColumn(6).setPreferredWidth(10);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 160, 690, 300));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        close.setContentAreaFilled(false);
        close.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeMouseMoved(evt);
            }
        });
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel3.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 30, 30));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimize.setContentAreaFilled(false);
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        jPanel3.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 30, 30));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel3.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Student's List");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 230, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 30));

        Shadow.setBackground(new java.awt.Color(0, 123, 123));
        Shadow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Shadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 710, 10));

        jPanel5.setBackground(new java.awt.Color(51, 66, 70));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Class");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 30));

        cls.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cls.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All_Student", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", " " }));
        cls.setBorder(null);
        cls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clsActionPerformed(evt);
            }
        });
        jPanel5.add(cls, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, 30));

        Submit.setBackground(new java.awt.Color(0, 153, 153));
        Submit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Submit.setText("Submit");
        Submit.setOpaque(true);
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubmitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SubmitMouseReleased(evt);
            }
        });
        jPanel5.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 30));

        Reset.setBackground(new java.awt.Color(255, 51, 51));
        Reset.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Reset.setForeground(new java.awt.Color(255, 255, 255));
        Reset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reset.setText("Reset");
        Reset.setOpaque(true);
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ResetMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ResetMouseReleased(evt);
            }
        });
        jPanel5.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 100, 30));

        dept.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Science ", "Commerce", "Arts" }));
        dept.setBorder(null);
        jPanel5.add(dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Department");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 110, 30));

        section.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        section.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "A", "B", "C", "D", "E" }));
        section.setBorder(null);
        jPanel5.add(section, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 150, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Section");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 110, 30));

        year.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2014", "2015", "2016", "2017", "2018", "2019" }));
        year.setSelectedIndex(4);
        year.setBorder(null);
        jPanel5.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 160, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Year");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 110, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 710, 110));

        copyright.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        copyright.setForeground(new java.awt.Color(51, 51, 51));
        copyright.setText("All Rights Reserved © Kochi lnc. 2018");
        jPanel1.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 220, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseMoved

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered

    }//GEN-LAST:event_closeMouseEntered

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        DashBoard back = new DashBoard();
        back.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation( x - xx , y - xy );
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        try{
            conn = DatabaseConnection.ConnectDB();
            int Y = 0 ;
            String sql = "select Year_Id from Year where Year = '"+year.getSelectedItem()+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if( rs.next() ){
                Y = rs.getInt("Year_Id");
            }
            pst.close();rs.close();
            int i = cls.getSelectedIndex();
            if( i == 0 ){
                if(dept.getSelectedIndex() == 0 ){
                    sql = "select distinct sai.Student_Id , Student_Name , c.Class_Name,Class_Roll,sc.Section_Name,y.Year\n" +
                        "from StudentAccademicInfo sai inner join StudentPersonalInfo spi on sai.Student_Id = spi.Student_Id\n" +
                        "inner join Class c on sai.Class_Id = c.Class_Id inner join Section sc on sai.Section_Id = sc.Section_Id\n" +
                        "inner join Year y on sai.Year_Id = y.Year_Id\n" +
                        "where sai.Year_Id = "+Y+"";
                    pst = conn.prepareStatement(sql);
                    rs = pst.executeQuery();
                    SList.setModel(DbUtils.resultSetToTableModel(rs));
                    pst.close();rs.close();
                }else{
                    sql = "select distinct sai.Student_Id , Student_Name , c.Class_Name,Class_Roll,sc.Section_Name,sai.Depertment_Name as Department , y.Year\n" +
                        "from StudentAccademicInfo sai inner join StudentPersonalInfo spi on sai.Student_Id = spi.Student_Id\n" +
                        "inner join Class c on sai.Class_Id = c.Class_Id inner join Section sc on sai.Section_Id = sc.Section_Id\n" +
                        "inner join Year y on sai.Year_Id = y.Year_Id \n" +
                        "where y.Year_Id = "+Y+" and sai.Depertment_Name = '"+dept.getSelectedItem()+"'";
                    pst = conn.prepareStatement(sql);
                    rs = pst.executeQuery();
                    SList.setModel(DbUtils.resultSetToTableModel(rs));
                    pst.close();rs.close();
                }
            }else if( i >= 1 && i <= 10 ){
                
                // Getting Class Id from Class Table
                int Scls = 0 ;
                sql = "Select Class_Id from Class where Class_Name = '"+cls.getSelectedItem()+"'";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                if( rs.next() ){
                    Scls = rs.getInt("Class_Id");
                }
                pst.close();rs.close();
                
                // Getting Section Id from Section Table
                int Ssec = 0 ;
                sql = "Select Section_Id from Section where Section_Name = '"+section.getSelectedItem()+"'";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                if( rs.next() ){
                    Ssec = rs.getInt("Section_Id");
                }
                pst.close();rs.close();
                int di = dept.getSelectedIndex();
                if( di == 0 ){
                    sql = "select distinct sai.Student_Id , Student_Name , c.Class_Name,Class_Roll,sc.Section_Name,y.Year\n" +
                    "from StudentAccademicInfo sai inner join StudentPersonalInfo spi on sai.Student_Id = spi.Student_Id\n" +
                    "inner join Class c on sai.Class_Id = c.Class_Id inner join Section sc on sai.Section_Id = sc.Section_Id\n" +
                    "inner join Year y on sai.Year_Id = y.Year_Id\n" +
                    "where c.Class_Id = "+Scls+" and sai.Year_Id = "+Y+"";
                if( Ssec == 0 ){
                    pst = conn.prepareStatement(sql);
                    rs = pst.executeQuery();
                    SList.setModel(DbUtils.resultSetToTableModel(rs));
                    pst.close();rs.close();
                }else{
                    String sql2 = sql + "and sc.Section_Id = "+Ssec+"";
                    pst = conn.prepareStatement(sql2);
                    rs = pst.executeQuery();
                    SList.setModel(DbUtils.resultSetToTableModel(rs));
                    pst.close();rs.close();
                }
                }else{
                    sql = "select distinct sai.Student_Id , Student_Name , c.Class_Name,Class_Roll,sc.Section_Name,sai.Depertment_Name as Department , y.Year\n" +
                        "from StudentAccademicInfo sai inner join StudentPersonalInfo spi on sai.Student_Id = spi.Student_Id\n" +
                        "inner join Class c on sai.Class_Id = c.Class_Id inner join Section sc on sai.Section_Id = sc.Section_Id\n" +
                        "inner join Year y on sai.Year_Id = y.Year_Id \n" +
                        "where y.Year_Id = "+Y+" and sai.Depertment_Name = '"+dept.getSelectedItem()+"'";
                    pst = conn.prepareStatement(sql);
                    rs = pst.executeQuery();
                    SList.setModel(DbUtils.resultSetToTableModel(rs));
                    pst.close();rs.close();
                }
            }
            
        }catch( Exception e ){ JOptionPane.showMessageDialog( null , e);} 
    }//GEN-LAST:event_SubmitMouseClicked

    private void SubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMousePressed
        Submit.setBackground(new java.awt.Color(0,122,122));
    }//GEN-LAST:event_SubmitMousePressed

    private void SubmitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseReleased
        Submit.setBackground(new java.awt.Color(0,153,153));
    }//GEN-LAST:event_SubmitMouseReleased

    private void ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseClicked
        DefaultTableModel model = (DefaultTableModel)SList.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_ResetMouseClicked

    private void ResetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMousePressed
        Reset.setBackground(new java.awt.Color(244,0,0));
    }//GEN-LAST:event_ResetMousePressed

    private void ResetMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseReleased
        Reset.setBackground(new java.awt.Color(255,51,51));
    }//GEN-LAST:event_ResetMouseReleased

    private void clsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clsActionPerformed
        int ind = cls.getSelectedIndex();
        if( ind >=1 && ind <= 8 ){
            dept.setEnabled(false);
            dept.setSelectedIndex(0);
        }else{
            dept.setEnabled(true);
            section.setEnabled(false);}
        if( ind == 0 || ind == 9 || ind == 10 ){
            section.setEnabled(false);
        }else{section.setEnabled(true);}
    }//GEN-LAST:event_clsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Students_List().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Reset;
    private javax.swing.JTable SList;
    private javax.swing.JPanel Shadow;
    private javax.swing.JLabel Submit;
    private javax.swing.JButton back;
    private javax.swing.JButton close;
    private javax.swing.JComboBox<String> cls;
    private javax.swing.JLabel copyright;
    private javax.swing.JComboBox<String> dept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton minimize;
    private javax.swing.JComboBox<String> section;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
