/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school.management.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author RK Anik
 */
public class Students_Info extends javax.swing.JFrame{

    /**
     * Creates new form Students_Info
     */
    
    public Students_Info() {
        initComponents();
    }
    int xx , xy ;
            
    Connection connection = null;
    PreparedStatement pst = null ;
    ResultSet rs = null ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        sclass = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        year = new javax.swing.JTextField();
        studentid = new javax.swing.JTextField();
        roll = new javax.swing.JTextField();
        dept = new javax.swing.JTextField();
        section = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel44 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        classroll1 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        classroll2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        fphn = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        classroll3 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        rel = new javax.swing.JTextField();
        sex = new javax.swing.JTextField();
        nation = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        mphn = new javax.swing.JTextField();
        doa = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        par_house = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        par_village = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        par_posto = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        par_postcode = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        par_district = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        par_subdistrict = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        par_division = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        par_country = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        pre_house = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        pre_village = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        pre_posto = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        pre_postcode = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        pre_district = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        pre_subdistrict = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        pre_division = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        pre_country = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        reset = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        close = new javax.swing.JButton();
        minimize = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        Shadow = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 30));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 140, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sclass.setEditable(false);
        sclass.setBackground(new java.awt.Color(239, 239, 239));
        sclass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sclass.setBorder(null);
        jPanel2.add(sclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 200, 25));

        jLabel43.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Academic Information");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 210, 25));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 790, 10));

        year.setEditable(false);
        year.setBackground(new java.awt.Color(239, 239, 239));
        year.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        year.setBorder(null);
        jPanel2.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 200, 25));

        studentid.setEditable(false);
        studentid.setBackground(new java.awt.Color(239, 239, 239));
        studentid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        studentid.setBorder(null);
        jPanel2.add(studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 200, 25));

        roll.setEditable(false);
        roll.setBackground(new java.awt.Color(239, 239, 239));
        roll.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        roll.setBorder(null);
        jPanel2.add(roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 200, 25));

        dept.setEditable(false);
        dept.setBackground(new java.awt.Color(239, 239, 239));
        dept.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dept.setBorder(null);
        jPanel2.add(dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 200, 25));

        section.setEditable(false);
        section.setBackground(new java.awt.Color(239, 239, 239));
        section.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        section.setBorder(null);
        jPanel2.add(section, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 200, 25));

        jLabel46.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Personal Information");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 190, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 790, 10));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(94, 94, 94));
        jLabel44.setText("Student's ID");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 100, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(94, 94, 94));
        jLabel16.setText("Student Class");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 30));

        classroll1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        classroll1.setForeground(new java.awt.Color(94, 94, 94));
        classroll1.setText("Class Roll");
        jPanel2.add(classroll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 90, 30));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(94, 94, 94));
        jLabel47.setText("Year");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 60, 30));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(94, 94, 94));
        jLabel48.setText("Section");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(94, 94, 94));
        jLabel19.setText("Department");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, 30));

        classroll2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        classroll2.setForeground(new java.awt.Color(94, 94, 94));
        classroll2.setText("Age");
        jPanel2.add(classroll2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 90, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(94, 94, 94));
        jLabel17.setText("Date of Birth");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 30));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(94, 94, 94));
        jLabel49.setText("Student Name");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 100, 30));

        name.setEditable(false);
        name.setBackground(new java.awt.Color(239, 239, 239));
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setBorder(null);
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 200, 25));

        dob.setEditable(false);
        dob.setBackground(new java.awt.Color(239, 239, 239));
        dob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dob.setBorder(null);
        jPanel2.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 200, 25));

        age.setEditable(false);
        age.setBackground(new java.awt.Color(239, 239, 239));
        age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        age.setBorder(null);
        jPanel2.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 200, 25));

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(94, 94, 94));
        jLabel50.setText("Father's Name");
        jPanel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, 30));

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(94, 94, 94));
        jLabel51.setText("Father Phone");
        jPanel2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, 30));

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(94, 94, 94));
        jLabel52.setText("Mother's Name");
        jPanel2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 100, 30));

        fname.setEditable(false);
        fname.setBackground(new java.awt.Color(239, 239, 239));
        fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fname.setBorder(null);
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 200, 25));

        fphn.setEditable(false);
        fphn.setBackground(new java.awt.Color(239, 239, 239));
        fphn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fphn.setBorder(null);
        jPanel2.add(fphn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 200, 25));

        mname.setEditable(false);
        mname.setBackground(new java.awt.Color(239, 239, 239));
        mname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mname.setBorder(null);
        jPanel2.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 200, 25));

        classroll3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        classroll3.setForeground(new java.awt.Color(94, 94, 94));
        classroll3.setText("Nationality");
        jPanel2.add(classroll3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 90, 30));

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(94, 94, 94));
        jLabel53.setText("Sex");
        jPanel2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 30));

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(94, 94, 94));
        jLabel54.setText("Religion");
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 100, 30));

        rel.setEditable(false);
        rel.setBackground(new java.awt.Color(239, 239, 239));
        rel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rel.setBorder(null);
        jPanel2.add(rel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 200, 25));

        sex.setEditable(false);
        sex.setBackground(new java.awt.Color(239, 239, 239));
        sex.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sex.setBorder(null);
        jPanel2.add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 200, 25));

        nation.setEditable(false);
        nation.setBackground(new java.awt.Color(239, 239, 239));
        nation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nation.setBorder(null);
        jPanel2.add(nation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 200, 25));

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(94, 94, 94));
        jLabel55.setText("Mother Phone");
        jPanel2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, 30));

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(94, 94, 94));
        jLabel56.setText("Date of Admission");
        jPanel2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, 30));

        mphn.setEditable(false);
        mphn.setBackground(new java.awt.Color(239, 239, 239));
        mphn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mphn.setBorder(null);
        jPanel2.add(mphn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 200, 25));

        doa.setEditable(false);
        doa.setBackground(new java.awt.Color(239, 239, 239));
        doa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        doa.setBorder(null);
        jPanel2.add(doa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 200, 25));

        jLabel57.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("Address");
        jPanel2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 190, 40));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 780, 10));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setForeground(new java.awt.Color(94, 94, 94));
        jLabel20.setText("House/Road:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        par_house.setEditable(false);
        par_house.setBackground(new java.awt.Color(239, 239, 239));
        par_house.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        par_house.setBorder(null);
        jPanel4.add(par_house, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 190, 20));

        jLabel21.setForeground(new java.awt.Color(94, 94, 94));
        jLabel21.setText("Village:");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        par_village.setEditable(false);
        par_village.setBackground(new java.awt.Color(239, 239, 239));
        par_village.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        par_village.setBorder(null);
        jPanel4.add(par_village, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 190, 20));

        jLabel22.setForeground(new java.awt.Color(94, 94, 94));
        jLabel22.setText("Post Office");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        par_posto.setEditable(false);
        par_posto.setBackground(new java.awt.Color(239, 239, 239));
        par_posto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        par_posto.setBorder(null);
        jPanel4.add(par_posto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 190, 20));

        jLabel23.setForeground(new java.awt.Color(94, 94, 94));
        jLabel23.setText("PostCode/Zip:");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        par_postcode.setEditable(false);
        par_postcode.setBackground(new java.awt.Color(239, 239, 239));
        par_postcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        par_postcode.setBorder(null);
        jPanel4.add(par_postcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 190, 20));

        jLabel24.setForeground(new java.awt.Color(94, 94, 94));
        jLabel24.setText("District:");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        par_district.setEditable(false);
        par_district.setBackground(new java.awt.Color(239, 239, 239));
        par_district.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        par_district.setBorder(null);
        jPanel4.add(par_district, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 190, 20));

        jLabel26.setForeground(new java.awt.Color(94, 94, 94));
        jLabel26.setText("Sub-District:");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        par_subdistrict.setEditable(false);
        par_subdistrict.setBackground(new java.awt.Color(239, 239, 239));
        par_subdistrict.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        par_subdistrict.setBorder(null);
        jPanel4.add(par_subdistrict, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 190, 20));

        jLabel25.setForeground(new java.awt.Color(94, 94, 94));
        jLabel25.setText("Division:");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        par_division.setEditable(false);
        par_division.setBackground(new java.awt.Color(239, 239, 239));
        par_division.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        par_division.setBorder(null);
        jPanel4.add(par_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 190, 20));

        jLabel58.setForeground(new java.awt.Color(94, 94, 94));
        jLabel58.setText("Country:");
        jPanel4.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        par_country.setEditable(false);
        par_country.setBackground(new java.awt.Color(239, 239, 239));
        par_country.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        par_country.setBorder(null);
        jPanel4.add(par_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 190, 20));

        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel59.setText("Parmanent Address");
        jPanel4.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 120, 20));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 360, 190));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setBackground(new java.awt.Color(0, 153, 153));
        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Present Address");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 120, 20));

        jLabel28.setBackground(new java.awt.Color(0, 0, 0));
        jLabel28.setForeground(new java.awt.Color(94, 94, 94));
        jLabel28.setText("House/Road:");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        pre_house.setEditable(false);
        pre_house.setBackground(new java.awt.Color(239, 239, 239));
        pre_house.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pre_house.setBorder(null);
        jPanel7.add(pre_house, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 190, 20));

        jLabel29.setForeground(new java.awt.Color(94, 94, 94));
        jLabel29.setText("Village:");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        pre_village.setEditable(false);
        pre_village.setBackground(new java.awt.Color(239, 239, 239));
        pre_village.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pre_village.setBorder(null);
        jPanel7.add(pre_village, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 190, 20));

        jLabel30.setForeground(new java.awt.Color(94, 94, 94));
        jLabel30.setText("Post Office");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        pre_posto.setEditable(false);
        pre_posto.setBackground(new java.awt.Color(239, 239, 239));
        pre_posto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pre_posto.setBorder(null);
        jPanel7.add(pre_posto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 190, 20));

        jLabel31.setForeground(new java.awt.Color(94, 94, 94));
        jLabel31.setText("PostCode/Zip:");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        pre_postcode.setEditable(false);
        pre_postcode.setBackground(new java.awt.Color(239, 239, 239));
        pre_postcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pre_postcode.setBorder(null);
        jPanel7.add(pre_postcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 190, 20));

        jLabel32.setForeground(new java.awt.Color(94, 94, 94));
        jLabel32.setText("District:");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        pre_district.setEditable(false);
        pre_district.setBackground(new java.awt.Color(239, 239, 239));
        pre_district.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pre_district.setBorder(null);
        jPanel7.add(pre_district, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 190, 20));

        jLabel33.setForeground(new java.awt.Color(94, 94, 94));
        jLabel33.setText("Sub-District:");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        pre_subdistrict.setEditable(false);
        pre_subdistrict.setBackground(new java.awt.Color(239, 239, 239));
        pre_subdistrict.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pre_subdistrict.setBorder(null);
        jPanel7.add(pre_subdistrict, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 190, 20));

        jLabel34.setForeground(new java.awt.Color(94, 94, 94));
        jLabel34.setText("Division:");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        pre_division.setEditable(false);
        pre_division.setBackground(new java.awt.Color(239, 239, 239));
        pre_division.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pre_division.setBorder(null);
        jPanel7.add(pre_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 190, 20));

        jLabel35.setForeground(new java.awt.Color(94, 94, 94));
        jLabel35.setText("Country:");
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        pre_country.setEditable(false);
        pre_country.setBackground(new java.awt.Color(239, 239, 239));
        pre_country.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pre_country.setBorder(null);
        jPanel7.add(pre_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 190, 20));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 360, 190));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 770, -1));

        jPanel3.setBackground(new java.awt.Color(54, 71, 75));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel3.setName(""); // NOI18N
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Student's ID");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 90, -1));

        id.setBackground(new java.awt.Color(61, 79, 83));
        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.setBorder(null);
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 250, 30));

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        search.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.setContentAreaFilled(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 140, 30));

        jPanel12.setBackground(new java.awt.Color(255, 51, 51));

        reset.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("Reset");
        reset.setContentAreaFilled(false);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, 30));

        jPanel13.setBackground(new java.awt.Color(0, 153, 153));
        jPanel13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel13MouseDragged(evt);
            }
        });
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel13MousePressed(evt);
            }
        });
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        close.setContentAreaFilled(false);
        close.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeMouseMoved(evt);
            }
        });
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel13.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 30, 30));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimize.setContentAreaFilled(false);
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        jPanel13.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 30, 30));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel13.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Student's Finder");
        jPanel13.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 320, 30));

        jPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        Shadow.setBackground(new java.awt.Color(0, 123, 123));
        Shadow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(Shadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, 10));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("All Rights Reserved © Kochi lnc. 2018");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 180, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 710));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 711, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try{ 
            connection = DatabaseConnection.ConnectDB();
            String query = "select Student_Id,MAX(Class_Id) as Class_Id,Section_Id,Depertment_Name,"+
                "MAX(Year_Id) as Year_Id\n" +
                "from StudentAccademicInfo where Student_Id = '"+id.getText()+"'\n" +
                "group by Student_Id , Section_Id,Depertment_Name";
            pst = connection.prepareStatement(query);
            rs = pst.executeQuery();
            if( rs.next()){
                studentid.setText(rs.getString("Student_Id"));
                dept.setText(rs.getString("Depertment_Name"));
                
                /* Getting Class Name from Class Table */ 
                String qu = "select Class_Name from Class where Class_Id = "+rs.getInt("Class_Id")+"";
                PreparedStatement ps = connection.prepareStatement(qu);
                ResultSet rset = ps.executeQuery();
                if( rset.next() ){
                    sclass.setText(rset.getString("Class_Name"));
                }
                ps.close();rset.close();
                
                /* Getting Section Name from Section Table */ 
                qu = "select Section_Name from Section where Section_Id = "+rs.getInt("Section_Id")+"";
                ps = connection.prepareStatement(qu);
                rset = ps.executeQuery();
                if( rset.next() ){
                    section.setText(rset.getString("Section_Name"));
                }
                ps.close();rset.close();
                
                /* Getting Year Name from Year Table */ 
                qu = "select Year from Year where Year_Id = "+rs.getInt("Year_Id")+"";
                ps = connection.prepareStatement(qu);
                rset = ps.executeQuery();
                if( rset.next() ){
                    year.setText(rset.getString("Year"));
                }
                ps.close();rset.close();
                
                ResultSet rs2 ;
                String query2 = "select * from StudentPersonalInfo where Student_Id = '"+id.getText()+"'";
                PreparedStatement pst2 = connection.prepareStatement(query2);
                rs2 = pst2.executeQuery();
                if(rs2.next()){
                    name.setText(rs2.getString("Student_Name"));
                    fname.setText(rs2.getString("Fathers_Name"));
                    fphn.setText(rs2.getString("Father_Phone_Number"));
                    mname.setText(rs2.getString("Mothers_Name"));
                    mphn.setText(rs2.getString("Mother_Phone_Number"));
                    dob.setText(rs2.getString("Date_Of_Birth"));
                    age.setText(rs2.getString("Age"));
                    rel.setText(rs2.getString("Religion"));
                    sex.setText(rs2.getString("Sex"));
                    doa.setText(rs2.getString("Admission_Date"));
                    nation.setText(rs2.getString("Nationality"));
                    
                }
                
                ResultSet rs3 ;
                String query3 = "select * from StudentPresentAddress where Student_Id = '"+id.getText()+"'";
                PreparedStatement pst3 = connection.prepareStatement(query3);
                rs3 = pst3.executeQuery();
                if(rs3.next()){
                    pre_house.setText(rs3.getString("HouseNo_Road"));
                    pre_village.setText(rs3.getString("Village"));
                    pre_posto.setText(rs3.getString("PostOffice"));
                    pre_postcode.setText(rs3.getString("PostalCode"));
                    pre_district.setText(rs3.getString("District"));
                    pre_subdistrict.setText(rs3.getString("SubDistrict"));
                    pre_division.setText(rs3.getString("Division"));
                    pre_country.setText(rs3.getString("Country"));  
                }
                
                ResultSet rs4 ;
                String query4 = "select * from StudentParmanentAddress where Student_Id = '"+id.getText()+"'";
                PreparedStatement pst4 = connection.prepareStatement(query4);
                rs4 = pst4.executeQuery();
                if(rs4.next()){
                    par_house.setText(rs4.getString("HouseNo_Road"));
                    par_village.setText(rs4.getString("Village"));
                    par_posto.setText(rs4.getString("PostOffice"));
                    par_postcode.setText(rs4.getString("PostalCode"));
                    par_district.setText(rs4.getString("District"));
                    par_subdistrict.setText(rs4.getString("SubDistrict"));
                    par_division.setText(rs4.getString("Division"));
                    par_country.setText(rs4.getString("Country"));  
                }
            }
            else{JOptionPane.showMessageDialog(null,"No Student Found!","Error",2 );}
        }
        catch(Exception e){JOptionPane.showMessageDialog(null, e );}
    }//GEN-LAST:event_searchActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation( x - xx , y - xy );
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void closeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseMoved

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered

    }//GEN-LAST:event_closeMouseEntered

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        DashBoard back = new DashBoard();
        back.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void jPanel13MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation( x - xx , y - xy );
    }//GEN-LAST:event_jPanel13MouseDragged

    private void jPanel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel13MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Students_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Students_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Students_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Students_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Students_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Shadow;
    private javax.swing.JTextField age;
    private javax.swing.JButton back;
    private javax.swing.JLabel classroll1;
    private javax.swing.JLabel classroll2;
    private javax.swing.JLabel classroll3;
    private javax.swing.JButton close;
    private javax.swing.JTextField dept;
    private javax.swing.JTextField doa;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField fphn;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton minimize;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField mphn;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nation;
    private javax.swing.JTextField par_country;
    private javax.swing.JTextField par_district;
    private javax.swing.JTextField par_division;
    private javax.swing.JTextField par_house;
    private javax.swing.JTextField par_postcode;
    private javax.swing.JTextField par_posto;
    private javax.swing.JTextField par_subdistrict;
    private javax.swing.JTextField par_village;
    private javax.swing.JTextField pre_country;
    private javax.swing.JTextField pre_district;
    private javax.swing.JTextField pre_division;
    private javax.swing.JTextField pre_house;
    private javax.swing.JTextField pre_postcode;
    private javax.swing.JTextField pre_posto;
    private javax.swing.JTextField pre_subdistrict;
    private javax.swing.JTextField pre_village;
    private javax.swing.JTextField rel;
    private javax.swing.JButton reset;
    private javax.swing.JTextField roll;
    private javax.swing.JTextField sclass;
    private javax.swing.JButton search;
    private javax.swing.JTextField section;
    private javax.swing.JTextField sex;
    private javax.swing.JTextField studentid;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
