/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school.management.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author RK Anik
 */
public class Subjects extends javax.swing.JFrame {

    /**
     * Creates new form Subjects
     */
    public Subjects() {
        initComponents();
        sc.setVisible(false);
        cm.setVisible(false);
        ar.setVisible(false);
    }
    Connection conn = null ;
    PreparedStatement pst = null;
    ResultSet rs = null ;
    int xx , xy ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        minimize1 = new javax.swing.JLabel();
        back1 = new javax.swing.JLabel();
        close1 = new javax.swing.JLabel();
        Shadow = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Sclass = new javax.swing.JComboBox<>();
        show = new javax.swing.JLabel();
        ar = new javax.swing.JLabel();
        sc = new javax.swing.JLabel();
        cm = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tsubject = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 70));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        jPanel2.setBackground(new java.awt.Color(54, 71, 75));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel6MouseDragged(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Subjects List");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 250, 30));

        minimize1.setBackground(new java.awt.Color(0, 153, 153));
        minimize1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimize1.setOpaque(true);
        minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimize1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimize1MouseReleased(evt);
            }
        });
        jPanel6.add(minimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 30, 30));

        back1.setBackground(new java.awt.Color(0, 153, 153));
        back1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        back1.setOpaque(true);
        back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                back1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                back1MouseReleased(evt);
            }
        });
        jPanel6.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        close1.setBackground(new java.awt.Color(0, 153, 153));
        close1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        close1.setOpaque(true);
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                close1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                close1MouseReleased(evt);
            }
        });
        jPanel6.add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 40, 30));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Shadow.setBackground(new java.awt.Color(0, 123, 123));
        Shadow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(Shadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 510, 7));

        jPanel4.setBackground(new java.awt.Color(0, 115, 115));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Select Class");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 30));

        Sclass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Sclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten" }));
        Sclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SclassActionPerformed(evt);
            }
        });
        jPanel4.add(Sclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, 32));

        show.setBackground(new java.awt.Color(51, 153, 255));
        show.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        show.setForeground(new java.awt.Color(255, 255, 255));
        show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show.setText("Show");
        show.setOpaque(true);
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                showMouseReleased(evt);
            }
        });
        jPanel4.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 220, 32));

        ar.setBackground(new java.awt.Color(0, 104, 104));
        ar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ar.setForeground(new java.awt.Color(255, 255, 255));
        ar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ar.setText("Arts");
        ar.setOpaque(true);
        ar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                arMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                arMouseReleased(evt);
            }
        });
        jPanel4.add(ar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 170, 30));

        sc.setBackground(new java.awt.Color(0, 104, 104));
        sc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sc.setForeground(new java.awt.Color(255, 255, 255));
        sc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sc.setText("Science");
        sc.setOpaque(true);
        sc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                scMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                scMouseReleased(evt);
            }
        });
        jPanel4.add(sc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 170, 30));

        cm.setBackground(new java.awt.Color(0, 104, 104));
        cm.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cm.setForeground(new java.awt.Color(255, 255, 255));
        cm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cm.setText("Commerce");
        cm.setOpaque(true);
        cm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmMouseReleased(evt);
            }
        });
        jPanel4.add(cm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 170, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 510, 110));

        Tsubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Code", "Subject Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tsubject.setGridColor(new java.awt.Color(255, 255, 255));
        Tsubject.setRowHeight(26);
        Tsubject.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane1.setViewportView(Tsubject);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 510, 250));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize1MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize1MouseClicked

    private void minimize1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize1MousePressed
        minimize1.setBackground(new java.awt.Color(0,123,123));
    }//GEN-LAST:event_minimize1MousePressed

    private void minimize1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize1MouseReleased
        minimize1.setBackground(new java.awt.Color(0,153,153));
    }//GEN-LAST:event_minimize1MouseReleased

    private void back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back1MouseClicked
        dispose();
        DashBoard back = new DashBoard();
        back.setVisible(true);
    }//GEN-LAST:event_back1MouseClicked

    private void back1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back1MousePressed
        back1.setBackground(new java.awt.Color(0,123,123));
    }//GEN-LAST:event_back1MousePressed

    private void back1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back1MouseReleased
        back1.setBackground(new java.awt.Color(0,153,153));
    }//GEN-LAST:event_back1MouseReleased

    private void close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_close1MouseClicked

    private void close1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MousePressed
        close1.setBackground(new java.awt.Color(0,123,123));

        System.exit(0);
    }//GEN-LAST:event_close1MousePressed

    private void close1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseReleased
        close1.setBackground(new java.awt.Color(0,153,153));
    }//GEN-LAST:event_close1MouseReleased

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx , y - xy );
    }//GEN-LAST:event_jPanel6MouseDragged

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel6MousePressed

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        try{
            conn = DatabaseConnection.ConnectDB();
            String q = "Select Class_Id from Class where Class_Name = '"+Sclass.getSelectedItem().toString()+"'";
            pst = conn.prepareStatement(q);
            rs = pst.executeQuery();
            if( rs.next() ){
                String q2 = "select Subject_Code,Subject_Name \n" +
                "from SubjectGenarate sg inner join Subject sb "+
                "on sg.Subject_Id = sb.Subject_Id\n" +
                "where Class_Id = "+rs.getInt("Class_Id")+"";
                PreparedStatement pst2 = conn.prepareStatement(q2);
                ResultSet rs2 = pst2.executeQuery();
                Tsubject.setModel(DbUtils.resultSetToTableModel(rs2));
            }
        }catch( Exception e ) {JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_showMouseClicked

    private void showMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMousePressed
        show.setBackground(new java.awt.Color(0,122,244));
    }//GEN-LAST:event_showMousePressed

    private void showMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseReleased
        show.setBackground(new java.awt.Color(51,153,255));
    }//GEN-LAST:event_showMouseReleased

    private void arMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arMouseClicked
        try{
            conn = DatabaseConnection.ConnectDB();
            String q2 = "select Subject_Code,Subject_Name\n" +
            "from DeptSubject dp inner join Subject sb "+
            "on dp.Subject_Id=sb.Subject_Id where Dept_Id=2";
            PreparedStatement pst = conn.prepareStatement(q2);
            ResultSet rs = pst.executeQuery();
            Tsubject.setModel(DbUtils.resultSetToTableModel(rs));  
        }catch(Exception e ){ JOptionPane.showMessageDialog( null, e);}
    }//GEN-LAST:event_arMouseClicked

    private void arMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arMousePressed
        ar.setBackground(new java.awt.Color(0,142,142));
        sc.setBackground(new java.awt.Color(0,104,104));
        cm.setBackground(new java.awt.Color(0,104,104));
    }//GEN-LAST:event_arMousePressed

    private void arMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_arMouseReleased

    private void scMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_scMouseClicked

    private void scMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scMousePressed
        sc.setBackground(new java.awt.Color(0,142,142));
        cm.setBackground(new java.awt.Color(0,104,104));
        ar.setBackground(new java.awt.Color(0,104,104));
        
        try{
            conn = DatabaseConnection.ConnectDB();
            String q2 = "select Subject_Code,Subject_Name\n" +
            "from DeptSubject dp inner join Subject sb "+
            "on dp.Subject_Id=sb.Subject_Id where Dept_Id=1";
            PreparedStatement pst = conn.prepareStatement(q2);
            ResultSet rs = pst.executeQuery();
            Tsubject.setModel(DbUtils.resultSetToTableModel(rs));  
        }catch(Exception e ){ JOptionPane.showMessageDialog( null, e);}
    }//GEN-LAST:event_scMousePressed

    private void scMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_scMouseReleased

    private void cmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmMouseClicked
        try{
            conn = DatabaseConnection.ConnectDB();
            String q2 = "select Subject_Code,Subject_Name\n" +
            "from DeptSubject dp inner join Subject sb "+
            "on dp.Subject_Id=sb.Subject_Id where Dept_Id=3";
            PreparedStatement pst = conn.prepareStatement(q2);
            ResultSet rs = pst.executeQuery();
            Tsubject.setModel(DbUtils.resultSetToTableModel(rs));  
        }catch(Exception e ){ JOptionPane.showMessageDialog( null, e);}
    }//GEN-LAST:event_cmMouseClicked

    private void cmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmMousePressed
        cm.setBackground(new java.awt.Color(0,142,142));
        sc.setBackground(new java.awt.Color(0,104,104));
        ar.setBackground(new java.awt.Color(0,104,104));
    }//GEN-LAST:event_cmMousePressed

    private void cmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmMouseReleased

    private void SclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SclassActionPerformed
        int i = Sclass.getSelectedIndex();
        if( i == 9 || i == 10 ){
            sc.setVisible(true);
            cm.setVisible(true);
            ar.setVisible(true);        
        }else{
            sc.setVisible(false);
            cm.setVisible(false);
            ar.setVisible(false);
        }
        cm.setBackground(new java.awt.Color(0,104,104));
        sc.setBackground(new java.awt.Color(0,104,104));
        ar.setBackground(new java.awt.Color(0,104,104));
    }//GEN-LAST:event_SclassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subjects().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Sclass;
    private javax.swing.JPanel Shadow;
    private javax.swing.JTable Tsubject;
    private javax.swing.JLabel ar;
    private javax.swing.JLabel back1;
    private javax.swing.JLabel close1;
    private javax.swing.JLabel cm;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel minimize1;
    private javax.swing.JLabel sc;
    private javax.swing.JLabel show;
    // End of variables declaration//GEN-END:variables
}
