/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school.management.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author RK Anik
 */
public class Update_Teacher_Info extends javax.swing.JFrame {

    /**
     * Creates new form Update_Student_Info
     */
    public Update_Teacher_Info() {
        initComponents();
    }

    int xx , xy ;
    Connection con = null ;
    PreparedStatement pst = null ;
    ResultSet rs = null ;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        close = new javax.swing.JButton();
        minimize = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        Shadow = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        whichupdate = new javax.swing.JComboBox<>();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        update = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        previousinfo = new javax.swing.JTextField();
        updateinfo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        reset = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        preorpar = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        address = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        Submit = new javax.swing.JButton();
        copyright = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 150));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        close.setContentAreaFilled(false);
        close.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeMouseMoved(evt);
            }
        });
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 30, 30));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimize.setContentAreaFilled(false);
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Information Updater");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 240, 30));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 30));

        Shadow.setBackground(new java.awt.Color(0, 123, 123));
        Shadow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Shadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 730, 10));

        jPanel4.setBackground(new java.awt.Color(49, 59, 60));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 123, 123)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 70, 20));

        whichupdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        whichupdate.setForeground(new java.awt.Color(255, 255, 255));
        whichupdate.setMaximumRowCount(20);
        whichupdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teacher_Name", "Contact_No", "Extra_Ordinary", "Fathers_Name", "Father_Phone_Number", "Mother_Name", "Mother_Phone_Number", "Qualification", "Date_Of_Birth", "Age", "Religion", "Sex", "Nationality", "Address" }));
        whichupdate.setBorder(null);
        jPanel4.add(whichupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 190, 30));

        id.setBackground(new java.awt.Color(61, 79, 83));
        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setForeground(new java.awt.Color(204, 204, 204));
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.setBorder(null);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel4.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 190, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Teacher ID");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, -1));

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        update.setBackground(new java.awt.Color(0, 153, 153));
        update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.setContentAreaFilled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 300, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Previous Info");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 100, -1));

        previousinfo.setEditable(false);
        previousinfo.setBackground(new java.awt.Color(61, 79, 83));
        previousinfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        previousinfo.setForeground(new java.awt.Color(204, 204, 204));
        previousinfo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        previousinfo.setBorder(null);
        previousinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousinfoActionPerformed(evt);
            }
        });
        jPanel4.add(previousinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 190, 90));

        updateinfo.setBackground(new java.awt.Color(61, 79, 83));
        updateinfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateinfo.setForeground(new java.awt.Color(204, 204, 204));
        updateinfo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updateinfo.setBorder(null);
        updateinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateinfoActionPerformed(evt);
            }
        });
        jPanel4.add(updateinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 630, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Updated Info");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 100, -1));

        jPanel7.setBackground(new java.awt.Color(204, 51, 0));

        reset.setBackground(new java.awt.Color(0, 153, 153));
        reset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("Reset");
        reset.setContentAreaFilled(false);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 190, -1));

        jPanel5.setBackground(new java.awt.Color(60, 69, 70));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        preorpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        preorpar.setForeground(new java.awt.Color(255, 255, 255));
        preorpar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Present Address", "Parmanent Address" }));
        preorpar.setBorder(null);
        jPanel5.add(preorpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 190, 30));

        jPanel8.setBackground(new java.awt.Color(0, 123, 123));

        jLabel7.setBackground(new java.awt.Color(51, 255, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Address");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 211, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 30));

        address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HouseNo_Road", "Village", "PostOffice", "PostalCode", "SubDistrict", "District", "Division", "Country" }));
        address.setBorder(null);
        jPanel5.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 190, 30));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 190, 155));

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));

        Submit.setBackground(new java.awt.Color(0, 153, 153));
        Submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setText("Submit");
        Submit.setContentAreaFilled(false);
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(Submit, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Submit, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 190, -1));

        copyright.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        copyright.setForeground(new java.awt.Color(153, 153, 153));
        copyright.setText("All Rights Reserved © Kochi lnc. 2018");
        jPanel4.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 210, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 730, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseMoved

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered

    }//GEN-LAST:event_closeMouseEntered

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx , y - xy );
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void previousinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousinfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previousinfoActionPerformed

    private void updateinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateinfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateinfoActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        try{
            Updated update = new Updated();
            con = DatabaseConnection.ConnectDB();
            
            if( updateinfo.getText().isEmpty() || id.getText().isEmpty() ){
                AdmissionErrors err = new AdmissionErrors();
                err.setVisible(true);
            }
            else{
                    int wu = whichupdate.getSelectedIndex();
                    if( wu == 0 || wu == 2 ){
                        String ifstpin = "update TeacherAccademicInfo set "+whichupdate.getSelectedItem()+" = '"+updateinfo.getText()+"' where Teacher_Id = '"+id.getText()+"'";
                        pst = con.prepareStatement(ifstpin);
                        pst.execute();
                        updateinfo.setText("");
                        update.setVisible(true);
                    }
                    if( wu == 1 || wu == 3 || wu == 4 || wu == 5 || wu == 6 || wu == 7 || wu == 9 || wu == 10 || wu == 11 || wu == 12 ){ 
                        String ifstpin = "update TeacherPersonalInfo set "+whichupdate.getSelectedItem()+" = '"+updateinfo.getText()+"' where Teacher_Id = '"+id.getText()+"'";
                        pst = con.prepareStatement(ifstpin);
                        pst.execute();
                        updateinfo.setText("");
                        update.setVisible(true);
                    }
                    else if( wu == 9 ){
                        String Sage = updateinfo.getText();
                        try{
                            int Iage = Integer.parseInt(Sage);
                            String ifstpin = "update TeacherPersonalInfo set "+whichupdate.getSelectedItem()+" = "+Iage+" where Teacher_Id = '"+id.getText()+"'";
                            pst = con.prepareStatement(ifstpin);
                            pst.execute();
                            updateinfo.setText("");
                            update.setVisible(true);
                        }
                        catch(Exception e ){
                            JOptionPane.showMessageDialog(null,"Age Must Have to be a Integer","Error!!!",2);
                        }
                        
                    }
                    else if( wu == 13 ){
                        int porp = preorpar.getSelectedIndex();
                        if( porp == 0 ){
                            int AD = address.getSelectedIndex();
                            if( AD == 0 || AD == 1 || AD == 2 || AD == 4 || AD == 5 || AD == 6 || AD == 7 ){
                                String ifstpread = "update TeacherPresentAddress set "+address.getSelectedItem()+" = '"+updateinfo.getText()+"' where Teacher_Id = '"+id.getText()+"'";
                                pst = con.prepareStatement(ifstpread);
                                pst.execute();
                                updateinfo.setText("");
                                update.setVisible(true);
                            }
                            if( AD == 3 ){
                                String Spc = updateinfo.getText();
                                try{
                                    int Ipc = Integer.parseInt(Spc);
                                    String ifstpread = "update TeacherPresentAddress set "+address.getSelectedItem()+" = "+Ipc+" where Teacher_Id = '"+id.getText()+"'";
                                    pst = con.prepareStatement(ifstpread);
                                    pst.execute();
                                    updateinfo.setText("");
                                    update.setVisible(true);
                                }catch(Exception e ){
                                    JOptionPane.showMessageDialog(null,"Postal Code Must Have to be a Integer","Error!!!",2);
                                }
                            }
                        }
                        else if( porp == 1 ){
                            int AD = address.getSelectedIndex();
                            if( AD == 0 || AD == 1 || AD == 2 || AD == 4 || AD == 5 || AD == 6 || AD == 7 ){
                                String ifstparad = "update TeacherParmanentAddress set "+address.getSelectedItem()+" = '"+updateinfo.getText()+"' where Teacher_Id = '"+id.getText()+"'";
                                pst = con.prepareStatement(ifstparad);
                                pst.execute();
                                updateinfo.setText("");
                                update.setVisible(true);
                            }
                            if( AD == 3 ){
                                String Spc = updateinfo.getText();
                                try{
                                    int Ipc = Integer.parseInt(Spc);
                                    String ifstparad = "update TeacherParmanentAddress set "+address.getSelectedItem()+" = "+Ipc+" where Teacher_Id = '"+id.getText()+"'";
                                    pst = con.prepareStatement(ifstparad);
                                    pst.execute();
                                    updateinfo.setText("");
                                    update.setVisible(true);
                                }catch(Exception e ){
                                    JOptionPane.showMessageDialog(null,"Postal Code Must Have to be a Integer","Error!!!",2);
                                }
                            }
                        }
                    }
            }
        
        }catch(Exception a ){ JOptionPane.showMessageDialog( null , a );}
    }//GEN-LAST:event_updateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        UpdaterLink update = new UpdaterLink();
        update.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        try{
            con = DatabaseConnection.ConnectDB();
            if(id.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Please Enter a ID then try again","Error!!!",2);
            }else{
                    int wu = whichupdate.getSelectedIndex();
                    if( wu == 0 || wu == 2 ){
                        String sql = "select "+whichupdate.getSelectedItem()+" from TeacherAccademicInfo where Teacher_Id = '"+id.getText()+"'";
                        pst =  con.prepareStatement(sql);
                        rs = pst.executeQuery();
                        if( rs.next() ){
                            previousinfo.setText( rs.getString(""+whichupdate.getSelectedItem()+""));
                        }
                    }
                    if( wu == 1 || wu == 3 || wu == 4 || wu == 5 || wu == 6 || wu == 7 || wu == 8 || wu == 9 || wu == 10 || wu == 11 || wu == 12){
                        String pinfo = "select "+whichupdate.getSelectedItem()+" from TeacherPersonalInfo where Teacher_Id = '"+id.getText()+"'";
                        pst =  con.prepareStatement(pinfo);
                        rs = pst.executeQuery();
                        if( rs.next() ){
                            previousinfo.setText( rs.getString(""+whichupdate.getSelectedItem()+""));
                        }
                    }
                    if( wu == 13 ){
                        int porp = preorpar.getSelectedIndex();
                        if( porp == 0 ){
                            int AD = address.getSelectedIndex();
                            if( AD == 0 || AD == 1 || AD == 2 || AD == 3 || AD == 4 || AD == 5 || AD == 6 || AD == 7 ){
                                String preadd = "select "+address.getSelectedItem()+" from TeacherPresentAddress where Teacher_Id = '"+id.getText()+"'";
                                pst =  con.prepareStatement(preadd);
                                rs = pst.executeQuery();
                                if( rs.next() ){
                                    previousinfo.setText( rs.getString(""+address.getSelectedItem()+""));
                                }
                            }
                        }
                        else if( porp == 1 ){
                            int AD = address.getSelectedIndex();
                            if( AD == 0 || AD == 1 || AD == 2 || AD == 3 || AD == 4 || AD == 5 || AD == 6 || AD == 7 ){
                                String paradd = "select "+address.getSelectedItem()+" from TeacherParmanentAddress where Teacher_Id = '"+id.getText()+"'";
                                pst =  con.prepareStatement(paradd);
                                rs = pst.executeQuery();
                                if( rs.next() ){
                                    previousinfo.setText( rs.getString(""+address.getSelectedItem()+""));
                                }
                            }
                        }
                    }
            }
            
        }catch(Exception e){JOptionPane.showMessageDialog(null, e );}
    }//GEN-LAST:event_SubmitActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed

        id.setText("");
        whichupdate.setSelectedIndex(0);
        previousinfo.setText("");
        updateinfo.setText("");
        preorpar.setSelectedIndex(0);
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Teacher_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Teacher_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Teacher_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Teacher_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Teacher_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Shadow;
    private javax.swing.JButton Submit;
    private javax.swing.JComboBox<String> address;
    private javax.swing.JButton back;
    private javax.swing.JButton close;
    private javax.swing.JLabel copyright;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton minimize;
    private javax.swing.JComboBox<String> preorpar;
    private javax.swing.JTextField previousinfo;
    private javax.swing.JButton reset;
    private javax.swing.JButton update;
    private javax.swing.JTextField updateinfo;
    private javax.swing.JComboBox<String> whichupdate;
    // End of variables declaration//GEN-END:variables
}
