/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school.management.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author RK Anik
 */
public class UploadMark extends javax.swing.JFrame {

    /**
     * Creates new form UploadMark
     */
    public UploadMark() {
        initComponents();
    }
    Connection conn = null ;
    PreparedStatement pst = null;
    ResultSet rs = null ;
    int xx, xy ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        exam = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Shadow = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        close = new javax.swing.JButton();
        minimize = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        showsub = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Sclass = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        subcode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mark = new javax.swing.JTextField();
        Refresh = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MarkList = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        Submit = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        reset = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tsubject = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(180, 70));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        jPanel2.setBackground(new java.awt.Color(51, 66, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setBackground(new java.awt.Color(75, 91, 94));
        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.setBorder(null);
        id.setCaretColor(new java.awt.Color(153, 255, 153));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 190, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Students Id");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 100, 30));

        exam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        exam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "First_Term", "Second_Term", "Final_Term" }));
        jPanel2.add(exam, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 200, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Exam");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 120, -1));

        Shadow.setBackground(new java.awt.Color(0, 123, 123));
        Shadow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(Shadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 990, 6));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        close.setContentAreaFilled(false);
        close.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeMouseMoved(evt);
            }
        });
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel3.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 40, 30));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimize.setContentAreaFilled(false);
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        jPanel3.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 30, 30));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel3.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mark Uploader");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 550, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 30));

        showsub.setBackground(new java.awt.Color(0, 153, 153));
        showsub.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        showsub.setForeground(new java.awt.Color(255, 255, 255));
        showsub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showsub.setText("Show Subjects");
        showsub.setOpaque(true);
        showsub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showsubMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showsubMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showsubMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                showsubMouseReleased(evt);
            }
        });
        jPanel2.add(showsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 220, 30));

        year.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "2014", "2015", "2016", "2017", "2018", "2019" }));
        jPanel2.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 210, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Year");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 50, 30));

        Sclass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Sclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine/Science", "Nine/Commerce", "Nine/Arts", "Ten/Science", "Ten/Commerce", "Ten/Arts" }));
        jPanel2.add(Sclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 220, 25));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Grade Point Table");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 220, 40));

        jPanel5.setBackground(new java.awt.Color(79, 91, 94));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subcode.setBackground(new java.awt.Color(61, 77, 81));
        subcode.setForeground(new java.awt.Color(255, 255, 255));
        subcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        subcode.setBorder(null);
        subcode.setCaretColor(new java.awt.Color(153, 255, 153));
        subcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subcodeActionPerformed(evt);
            }
        });
        jPanel5.add(subcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Subject Code");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 120, -1));

        mark.setBackground(new java.awt.Color(61, 77, 81));
        mark.setForeground(new java.awt.Color(255, 255, 255));
        mark.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mark.setBorder(null);
        mark.setCaretColor(new java.awt.Color(153, 255, 153));
        mark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markActionPerformed(evt);
            }
        });
        jPanel5.add(mark, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 190, 30));

        Refresh.setBackground(new java.awt.Color(0, 153, 153));
        Refresh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Refresh.setForeground(new java.awt.Color(255, 255, 255));
        Refresh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Refresh.setText("Refresh");
        Refresh.setOpaque(true);
        Refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefreshMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RefreshMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RefreshMouseReleased(evt);
            }
        });
        jPanel5.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 430, 30));

        MarkList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Code", " Mark", "Point", "Exam", "Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MarkList.setGridColor(new java.awt.Color(255, 255, 255));
        MarkList.setRowHeight(22);
        MarkList.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane2.setViewportView(MarkList);
        if (MarkList.getColumnModel().getColumnCount() > 0) {
            MarkList.getColumnModel().getColumn(0).setResizable(false);
            MarkList.getColumnModel().getColumn(1).setResizable(false);
            MarkList.getColumnModel().getColumn(2).setResizable(false);
            MarkList.getColumnModel().getColumn(3).setResizable(false);
            MarkList.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 430, 220));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mark List");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, -1));

        Submit.setBackground(new java.awt.Color(0, 153, 153));
        Submit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Submit.setText("Submit Mark");
        Submit.setOpaque(true);
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubmitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SubmitMouseReleased(evt);
            }
        });
        jPanel5.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Obtain Mark");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 130, -1));

        reset.setBackground(new java.awt.Color(255, 51, 51));
        reset.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reset.setText("Reset");
        reset.setOpaque(true);
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                resetMouseReleased(evt);
            }
        });
        jPanel5.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 120, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 450, 410));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"    80-100", "     5.00", "     A+"},
                {"    70-79", "     4.00", "     A"},
                {"    60-69", "     3.50", "     A-"},
                {"    50-59", "     3.00", "     B"},
                {"    40-49", "     2.00", "     C"},
                {"    33-39", "     1.00", "     D"},
                {"    00-32", "     0.00", "     F"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "   Interval", "Grade Point", "Letter Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(234, 234, 234));
        jTable1.setRowHeight(26);
        jScrollPane3.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 250, 380));

        Tsubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Code", "Subject Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tsubject.setGridColor(new java.awt.Color(255, 255, 255));
        Tsubject.setRowHeight(26);
        Tsubject.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane1.setViewportView(Tsubject);
        if (Tsubject.getColumnModel().getColumnCount() > 0) {
            Tsubject.getColumnModel().getColumn(0).setResizable(false);
            Tsubject.getColumnModel().getColumn(0).setPreferredWidth(12);
            Tsubject.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 250, 380));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Select Class");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 220, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void closeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseMoved

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered

    }//GEN-LAST:event_closeMouseEntered

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        DashBoard back = new DashBoard();
        back.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation( x - xx , y - xy );
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void showsubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showsubMouseClicked
        if( Sclass.getSelectedIndex() == 0 ){
            JOptionPane.showMessageDialog(null,"Please Select Class","Message",2);
        }else{
            try{
                conn = DatabaseConnection.ConnectDB();
                String q = "Select Class_Id from Class where Class_Name = '"+Sclass.getSelectedItem().toString()+"'";
                pst = conn.prepareStatement(q);
                rs = pst.executeQuery();
                int i = Sclass.getSelectedIndex();
                if( i == 9 || i == 12 ){
                    
                    String q2 = "select Subject_Code,Subject_Name\n" +
                                "from DeptSubject dp inner join Subject sb "
                                + "on dp.Subject_Id=sb.Subject_Id where Dept_Id=1";
                    PreparedStatement pst2 = conn.prepareStatement(q2);
                    ResultSet rs2 = pst2.executeQuery();
                    Tsubject.setModel(DbUtils.resultSetToTableModel(rs2));
                }else if( i == 10 || i == 13 ){
                    String q2 = "select Subject_Code,Subject_Name\n" +
                                "from DeptSubject dp inner join Subject sb "
                                + "on dp.Subject_Id=sb.Subject_Id where Dept_Id=3";
                    PreparedStatement pst2 = conn.prepareStatement(q2);
                    ResultSet rs2 = pst2.executeQuery();
                    Tsubject.setModel(DbUtils.resultSetToTableModel(rs2));
                }else if( i == 11 || i == 14 ){
                    String q2 = "select Subject_Code,Subject_Name\n" +
                                "from DeptSubject dp inner join Subject sb "
                                + "on dp.Subject_Id=sb.Subject_Id where Dept_Id=2";
                    PreparedStatement pst2 = conn.prepareStatement(q2);
                    ResultSet rs2 = pst2.executeQuery();
                    Tsubject.setModel(DbUtils.resultSetToTableModel(rs2));
                }else{
                    if( rs.next() ){
                        String q2 = "select Subject_Code,Subject_Name \n" +
                                "from SubjectGenarate sg inner join Subject sb "
                                + "on sg.Subject_Id = sb.Subject_Id\n" +
                                "where Class_Id = "+rs.getInt("Class_Id")+"";
                        PreparedStatement pst2 = conn.prepareStatement(q2);
                        ResultSet rs2 = pst2.executeQuery();
                        Tsubject.setModel(DbUtils.resultSetToTableModel(rs2));
                    }
                }
            
            }catch(Exception e ) {JOptionPane.showMessageDialog(null, e);}
        }
    }//GEN-LAST:event_showsubMouseClicked

    private void showsubMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showsubMousePressed
        showsub.setBackground(new java.awt.Color(0,122,122));
    }//GEN-LAST:event_showsubMousePressed

    private void showsubMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showsubMouseReleased
        showsub.setBackground(new java.awt.Color(0,153,153));
    }//GEN-LAST:event_showsubMouseReleased

    private void subcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subcodeActionPerformed

    private void markActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markActionPerformed

    private void RefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMouseClicked
        
        if(id.getText().isEmpty() || Sclass.getSelectedIndex() == 0 ){
            JOptionPane.showMessageDialog(null,"Please Enter a ID and Select Class","Message",2);
        }else{
            try{
                conn = DatabaseConnection.ConnectDB();
                int clsid = 0 , i = Sclass.getSelectedIndex() ;
                if( i == 9 || i == 10 || i == 11 ){
                    clsid = 9 ;
                }
                else if( i == 12 || i == 13 || i == 14 ){
                    clsid = 10 ;
                }else{
                    String q = "Select Class_Id from Class where "
                            + "Class_Name = '"+Sclass.getSelectedItem().toString()+"'";
                    pst = conn.prepareStatement(q);
                    rs = pst.executeQuery();
                    if( rs.next() ){
                        clsid = rs.getInt("Class_Id");
                    }
                }
                int exm = exam.getSelectedIndex();
                if( exm == 0 ){
                    String q2 = "select Subject_Code,Obtained_Marks,Grade_Point,Year\n" +
                            "from Marks mr inner join Subject sb on mr.Subject_Id = sb.Subject_Id\n" +
                            "inner join Year y on mr.Year_Id = y.Year_Id\n" +
                            "inner join GradePoint gp on mr.Grade_Id = gp.Grade_Id"+
                            " where Student_Id = '"+id.getText()+"' and Class_Id = "+clsid+"";
                    PreparedStatement pst2 = conn.prepareStatement(q2);
                    ResultSet rs2 = pst2.executeQuery();
                    MarkList.setModel(DbUtils.resultSetToTableModel(rs2));
                }else if( exm == 1 ){
                    String q2 = "select Subject_Code,Obtained_Marks as Mark,Grade_Point as Point,Exam_Name as Exam,Year\n" +
                                "from Marks mr inner join Subject sb on mr.Subject_Id = sb.Subject_Id\n" +
                                "inner join Year y on mr.Year_Id = y.Year_Id\n" +
                                "inner join GradePoint gp on mr.Grade_Id = gp.Grade_Id\n" +
                                "inner join Examination ex on mr.Exam_Id = ex.Exam_Id\n" +
                                "where Student_Id = '"+id.getText()+"' and Class_Id = "+clsid+" and ex.Exam_Id = 1";
                    PreparedStatement pst2 = conn.prepareStatement(q2);
                    ResultSet rs2 = pst2.executeQuery();
                    MarkList.setModel(DbUtils.resultSetToTableModel(rs2));
                }else if( exm == 2 ){
                    String q2 = "select Subject_Code,Obtained_Marks as Mark,Grade_Point as Point,Exam_Name as Exam,Year\n" +
                                "from Marks mr inner join Subject sb on mr.Subject_Id = sb.Subject_Id\n" +
                                "inner join Year y on mr.Year_Id = y.Year_Id\n" +
                                "inner join GradePoint gp on mr.Grade_Id = gp.Grade_Id\n" +
                                "inner join Examination ex on mr.Exam_Id = ex.Exam_Id\n" +
                                "where Student_Id = '"+id.getText()+"' and Class_Id = "+clsid+" and ex.Exam_Id = 2";
                    PreparedStatement pst2 = conn.prepareStatement(q2);
                    ResultSet rs2 = pst2.executeQuery();
                    MarkList.setModel(DbUtils.resultSetToTableModel(rs2));
                    
                }else if( exm == 3 ){
                    String q2 = "select Subject_Code,Obtained_Marks as Mark,Grade_Point as Point,Exam_Name as Exam,Year\n" +
                                "from Marks mr inner join Subject sb on mr.Subject_Id = sb.Subject_Id\n" +
                                "inner join Year y on mr.Year_Id = y.Year_Id\n" +
                                "inner join GradePoint gp on mr.Grade_Id = gp.Grade_Id\n" +
                                "inner join Examination ex on mr.Exam_Id = ex.Exam_Id\n" +
                                "where Student_Id = '"+id.getText()+"' and Class_Id = "+clsid+" and ex.Exam_Id = 3";
                    PreparedStatement pst2 = conn.prepareStatement(q2);
                    ResultSet rs2 = pst2.executeQuery();
                    MarkList.setModel(DbUtils.resultSetToTableModel(rs2));
                }  
            }catch(Exception e ) {JOptionPane.showMessageDialog(null, e);}
        }  
    }//GEN-LAST:event_RefreshMouseClicked

    private void RefreshMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMousePressed
        Refresh.setBackground(new java.awt.Color(0,122,122));
    }//GEN-LAST:event_RefreshMousePressed

    private void RefreshMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMouseReleased
        Refresh.setBackground(new java.awt.Color(0,153,153));
    }//GEN-LAST:event_RefreshMouseReleased

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        if( id.getText().isEmpty() || exam.getSelectedIndex() == 0 || year.getSelectedIndex() == 0 || mark.getText().isEmpty() || subcode.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null,"Fill Up Fields Properly","Message",2);
        }else{
            try{
                conn = DatabaseConnection.ConnectDB();
                String q1 = "Select Max(Class_Id) as Class_Id from StudentAccademicInfo where Student_Id = '"+id.getText()+"'";
                pst = conn.prepareStatement(q1);
                rs = pst.executeQuery();
                if( rs.next() ){
                    int clsid = Integer.parseInt( rs.getString("Class_Id"));
                    
                    String q2 = "select Exam_Id from Examination where Exam_Name = '"+exam.getSelectedItem().toString()+"'";
                    PreparedStatement pst2 = conn.prepareStatement(q2);
                    ResultSet rs2 = pst2.executeQuery();
                    int examid = 0 ;
                    if( rs2.next() ){
                        examid = Integer.parseInt( rs2.getString("Exam_Id"));
                    }
                    String q3="select Subject_Id from Subject where Subject_Code = '"+subcode.getText()+"'";
                    PreparedStatement pst3 = conn.prepareStatement(q3);
                    ResultSet rs3 = pst3.executeQuery();
                    int sbid  = 0 ;
                    if( rs3.next() ){
                        sbid = Integer.parseInt( rs3.getString("Subject_Id"));
                    }
                    String q4 = "select Year_Id from Year where Year = "+year.getSelectedItem().toString()+"";
                    PreparedStatement pst4 = conn.prepareStatement(q4);
                    ResultSet rs4 = pst4.executeQuery();
                    int yid =  0 ;
                    if( rs4.next() ){
                        yid = Integer.parseInt( rs4.getString("Year_Id"));
                    }
                    
                    int Grade_Id = 0 , obmk = Integer.parseInt(mark.getText());
                    if( obmk >= 80 && obmk <=100 ){Grade_Id =1 ;}else if( obmk >= 70 && obmk <80 ){Grade_Id = 2;}
                    else if( obmk >= 60 && obmk < 70 ){Grade_Id = 3;}else if( obmk >= 50 && obmk < 60 ){Grade_Id = 4;}
                    else if( obmk >= 40 && obmk < 50 ){Grade_Id = 5;}else if( obmk >= 33 && obmk < 40 ){Grade_Id = 6;}
                    else if( obmk >= 0 && obmk < 33 ){Grade_Id = 7;}
                    
                    String a = "select Subject_Code from Subject where Subject_Code=?";
                    PreparedStatement pst12 = conn.prepareStatement(a);
                    pst12.setString(1, subcode.getText());
                    ResultSet rs10 = pst12.executeQuery();
                    if( rs10.next() ){
                        try{
                            String q5 = "insert into Marks values("+clsid+","+examid+",'"+id.getText()+"',"+sbid+","+obmk+","+Grade_Id+","+yid+")";
                            PreparedStatement pst5 = conn.prepareStatement(q5);
                            pst5.execute();
                            subcode.setText("");mark.setText("");
                            JOptionPane.showMessageDialog(null,"Marks Succesfully Inserted\nClick Refresh to Check");
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(null,"Mark Already Updated");
                        }
                    }else{JOptionPane.showMessageDialog(null,"Subject Code Not Found!!");}
                     
                }
                
            }catch(Exception e ) {JOptionPane.showMessageDialog(null, e);}
        }
 
    }//GEN-LAST:event_SubmitMouseClicked

    private void SubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitMousePressed

    private void SubmitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitMouseReleased

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        id.setText("ST-");exam.setSelectedIndex(0);year.setSelectedIndex(0);
        subcode.setText("");mark.setText("");
        DefaultTableModel model = (DefaultTableModel)Tsubject.getModel();
        model.setRowCount(0);
        DefaultTableModel model2 = (DefaultTableModel)MarkList.getModel();
        model2.setRowCount(0);
    }//GEN-LAST:event_resetMouseClicked

    private void resetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetMousePressed

    private void resetMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_resetMouseReleased

    private void showsubMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showsubMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_showsubMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UploadMark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UploadMark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UploadMark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UploadMark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UploadMark().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MarkList;
    private javax.swing.JLabel Refresh;
    private javax.swing.JComboBox<String> Sclass;
    private javax.swing.JPanel Shadow;
    private javax.swing.JLabel Submit;
    private javax.swing.JTable Tsubject;
    private javax.swing.JButton back;
    private javax.swing.JButton close;
    private javax.swing.JComboBox<String> exam;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mark;
    private javax.swing.JButton minimize;
    private javax.swing.JLabel reset;
    private javax.swing.JLabel showsub;
    private javax.swing.JTextField subcode;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
