/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school.management.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author RK Anik
 */
public class Worker_Info extends javax.swing.JFrame {

    /**
     * Creates new form Teachers_Info
     */
    public Worker_Info() {
        initComponents();
    }
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null ;
    int xx , xy ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        show = new javax.swing.JLabel();
        reset = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        Shadow = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        teacherid = new javax.swing.JTextField();
        teachername = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        rank = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        dateofjoin = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfathername = new javax.swing.JTextField();
        tmothername = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fatherphnno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        motherphnno = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tage = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tsex = new javax.swing.JTextField();
        treligion = new javax.swing.JTextField();
        tnationality = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tspeciality = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel41 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        pre_house = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        pre_village = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        pre_town = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        pre_postcode = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        pre_district = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        pre_subdistrict = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        pre_division = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        pre_country = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        par_house = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        par_village = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        par_town = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        par_postcode = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        par_district = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        par_subdistrict = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        par_division = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        par_country = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 50));
        setUndecorated(true);
        setResizable(false);

        Back.setBackground(new java.awt.Color(255, 255, 255));
        Back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        Back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(54, 71, 75));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel3.setName(""); // NOI18N
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Worker's ID  :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 110, 30));

        id.setBackground(new java.awt.Color(61, 79, 83));
        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setForeground(new java.awt.Color(204, 204, 204));
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.setBorder(null);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 250, 30));

        show.setBackground(new java.awt.Color(51, 153, 255));
        show.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        show.setForeground(new java.awt.Color(255, 255, 255));
        show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show.setText("Show");
        show.setOpaque(true);
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                showMouseReleased(evt);
            }
        });
        jPanel3.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 140, 30));

        reset.setBackground(new java.awt.Color(255, 51, 0));
        reset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reset.setText("Reset");
        reset.setOpaque(true);
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                resetMouseReleased(evt);
            }
        });
        jPanel3.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 140, 30));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Worker's Information");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 240, 30));

        minimize.setBackground(new java.awt.Color(0, 153, 153));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimize.setOpaque(true);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimizeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizeMouseReleased(evt);
            }
        });
        jPanel5.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 30, 30));

        back.setBackground(new java.awt.Color(0, 153, 153));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        back.setOpaque(true);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backMouseReleased(evt);
            }
        });
        jPanel5.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        close.setBackground(new java.awt.Color(0, 153, 153));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        close.setOpaque(true);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });
        jPanel5.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 40, 30));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        Shadow.setBackground(new java.awt.Color(0, 123, 123));
        Shadow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(Shadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, 7));

        Back.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Personal Information");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 190, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 780, 10));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(74, 74, 74));
        jLabel36.setText("Worker's ID           :");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 120, 20));

        teacherid.setEditable(false);
        teacherid.setBackground(new java.awt.Color(239, 239, 239));
        teacherid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        teacherid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        teacherid.setBorder(null);
        jPanel1.add(teacherid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 200, 28));

        teachername.setEditable(false);
        teachername.setBackground(new java.awt.Color(239, 239, 239));
        teachername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        teachername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        teachername.setBorder(null);
        jPanel1.add(teachername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 200, 28));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(74, 74, 74));
        jLabel10.setText("Worker's Name      :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 120, 20));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(74, 74, 74));
        jLabel37.setText("Designation              :");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 130, 20));

        rank.setEditable(false);
        rank.setBackground(new java.awt.Color(239, 239, 239));
        rank.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rank.setBorder(null);
        jPanel1.add(rank, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 200, 28));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(74, 74, 74));
        jLabel38.setText("Date Of Join             :");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 130, 20));

        dateofjoin.setEditable(false);
        dateofjoin.setBackground(new java.awt.Color(239, 239, 239));
        dateofjoin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateofjoin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dateofjoin.setBorder(null);
        jPanel1.add(dateofjoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 200, 28));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 780, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 780, 10));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Academic Information");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 210, 25));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(74, 74, 74));
        jLabel11.setText("Father's Name         :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 120, 20));

        tfathername.setEditable(false);
        tfathername.setBackground(new java.awt.Color(239, 239, 239));
        tfathername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfathername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfathername.setBorder(null);
        jPanel1.add(tfathername, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 200, 28));

        tmothername.setEditable(false);
        tmothername.setBackground(new java.awt.Color(239, 239, 239));
        tmothername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tmothername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tmothername.setBorder(null);
        jPanel1.add(tmothername, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 200, 28));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(74, 74, 74));
        jLabel12.setText("Mather's Name        :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 120, 20));

        fatherphnno.setEditable(false);
        fatherphnno.setBackground(new java.awt.Color(239, 239, 239));
        fatherphnno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fatherphnno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fatherphnno.setBorder(null);
        jPanel1.add(fatherphnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 200, 28));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(74, 74, 74));
        jLabel13.setText("Phone Number        :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 130, 20));

        motherphnno.setEditable(false);
        motherphnno.setBackground(new java.awt.Color(239, 239, 239));
        motherphnno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        motherphnno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        motherphnno.setBorder(null);
        jPanel1.add(motherphnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 200, 28));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(74, 74, 74));
        jLabel14.setText("Phone Number        :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 130, 20));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(74, 74, 74));
        jLabel15.setText("Age                      :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 120, 20));

        tage.setEditable(false);
        tage.setBackground(new java.awt.Color(239, 239, 239));
        tage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tage.setBorder(null);
        jPanel1.add(tage, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 200, 28));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(74, 74, 74));
        jLabel16.setText("Sex                      :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, 20));

        tsex.setEditable(false);
        tsex.setBackground(new java.awt.Color(239, 239, 239));
        tsex.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tsex.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tsex.setBorder(null);
        jPanel1.add(tsex, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 200, 28));

        treligion.setEditable(false);
        treligion.setBackground(new java.awt.Color(239, 239, 239));
        treligion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        treligion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        treligion.setBorder(null);
        jPanel1.add(treligion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 200, 28));

        tnationality.setEditable(false);
        tnationality.setBackground(new java.awt.Color(239, 239, 239));
        tnationality.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tnationality.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tnationality.setBorder(null);
        jPanel1.add(tnationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 200, 28));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(74, 74, 74));
        jLabel17.setText("Religion                 :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, 20));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(74, 74, 74));
        jLabel18.setText("Nationality               :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 130, 20));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(74, 74, 74));
        jLabel19.setText("Extra Ordinary        :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 120, 20));

        tspeciality.setEditable(false);
        tspeciality.setBackground(new java.awt.Color(239, 239, 239));
        tspeciality.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tspeciality.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tspeciality.setBorder(null);
        jPanel1.add(tspeciality, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 200, 28));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 780, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 780, 10));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Address");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 190, 40));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setBackground(new java.awt.Color(0, 153, 153));
        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Present Address");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 20));

        jLabel28.setBackground(new java.awt.Color(0, 0, 0));
        jLabel28.setForeground(new java.awt.Color(74, 74, 74));
        jLabel28.setText("House/Road:");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        pre_house.setEditable(false);
        pre_house.setBackground(new java.awt.Color(239, 239, 239));
        pre_house.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pre_house.setBorder(null);
        jPanel7.add(pre_house, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 170, 21));

        jLabel29.setForeground(new java.awt.Color(74, 74, 74));
        jLabel29.setText("Village:");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        pre_village.setEditable(false);
        pre_village.setBackground(new java.awt.Color(239, 239, 239));
        pre_village.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pre_village.setBorder(null);
        jPanel7.add(pre_village, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 170, 21));

        jLabel30.setForeground(new java.awt.Color(74, 74, 74));
        jLabel30.setText("Town/City:");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        pre_town.setEditable(false);
        pre_town.setBackground(new java.awt.Color(239, 239, 239));
        pre_town.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pre_town.setBorder(null);
        jPanel7.add(pre_town, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 170, 21));

        jLabel31.setForeground(new java.awt.Color(74, 74, 74));
        jLabel31.setText("PostCode/Zip:");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        pre_postcode.setEditable(false);
        pre_postcode.setBackground(new java.awt.Color(239, 239, 239));
        pre_postcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pre_postcode.setBorder(null);
        jPanel7.add(pre_postcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, 21));

        jLabel32.setForeground(new java.awt.Color(74, 74, 74));
        jLabel32.setText("District:");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        pre_district.setEditable(false);
        pre_district.setBackground(new java.awt.Color(239, 239, 239));
        pre_district.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pre_district.setBorder(null);
        jPanel7.add(pre_district, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 170, 21));

        jLabel33.setForeground(new java.awt.Color(74, 74, 74));
        jLabel33.setText("Sub-District:");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        pre_subdistrict.setEditable(false);
        pre_subdistrict.setBackground(new java.awt.Color(239, 239, 239));
        pre_subdistrict.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pre_subdistrict.setBorder(null);
        jPanel7.add(pre_subdistrict, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 170, 21));

        jLabel34.setForeground(new java.awt.Color(74, 74, 74));
        jLabel34.setText("Division:");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 20));

        pre_division.setEditable(false);
        pre_division.setBackground(new java.awt.Color(239, 239, 239));
        pre_division.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pre_division.setBorder(null);
        jPanel7.add(pre_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 170, 21));

        jLabel35.setForeground(new java.awt.Color(74, 74, 74));
        jLabel35.setText("Country:");
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        pre_country.setEditable(false);
        pre_country.setBackground(new java.awt.Color(239, 239, 239));
        pre_country.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pre_country.setBorder(null);
        jPanel7.add(pre_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 170, 21));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 340, 240));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setForeground(new java.awt.Color(74, 74, 74));
        jLabel20.setText("House/Road:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        par_house.setEditable(false);
        par_house.setBackground(new java.awt.Color(239, 239, 239));
        par_house.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        par_house.setBorder(null);
        jPanel4.add(par_house, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 190, 21));

        jLabel21.setForeground(new java.awt.Color(74, 74, 74));
        jLabel21.setText("Village:");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        par_village.setEditable(false);
        par_village.setBackground(new java.awt.Color(239, 239, 239));
        par_village.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        par_village.setBorder(null);
        jPanel4.add(par_village, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 190, 21));

        jLabel22.setForeground(new java.awt.Color(74, 74, 74));
        jLabel22.setText("Town/City:");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        par_town.setEditable(false);
        par_town.setBackground(new java.awt.Color(239, 239, 239));
        par_town.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        par_town.setBorder(null);
        jPanel4.add(par_town, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 190, 21));

        jLabel23.setForeground(new java.awt.Color(74, 74, 74));
        jLabel23.setText("PostCode/Zip:");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        par_postcode.setEditable(false);
        par_postcode.setBackground(new java.awt.Color(239, 239, 239));
        par_postcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        par_postcode.setBorder(null);
        jPanel4.add(par_postcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 190, 21));

        jLabel24.setForeground(new java.awt.Color(74, 74, 74));
        jLabel24.setText("District:");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        par_district.setEditable(false);
        par_district.setBackground(new java.awt.Color(239, 239, 239));
        par_district.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        par_district.setBorder(null);
        jPanel4.add(par_district, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 190, 21));

        jLabel26.setForeground(new java.awt.Color(74, 74, 74));
        jLabel26.setText("Sub-District:");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        par_subdistrict.setEditable(false);
        par_subdistrict.setBackground(new java.awt.Color(239, 239, 239));
        par_subdistrict.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        par_subdistrict.setBorder(null);
        jPanel4.add(par_subdistrict, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 190, 21));

        jLabel25.setForeground(new java.awt.Color(74, 74, 74));
        jLabel25.setText("Division:");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 20));

        par_division.setEditable(false);
        par_division.setBackground(new java.awt.Color(239, 239, 239));
        par_division.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        par_division.setBorder(null);
        jPanel4.add(par_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 190, 21));

        jLabel42.setForeground(new java.awt.Color(74, 74, 74));
        jLabel42.setText("Country:");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        par_country.setEditable(false);
        par_country.setBackground(new java.awt.Color(239, 239, 239));
        par_country.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        par_country.setBorder(null);
        jPanel4.add(par_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 190, 21));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel43.setText("Parmanent Address");
        jPanel4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 360, 240));

        contact.setEditable(false);
        contact.setBackground(new java.awt.Color(239, 239, 239));
        contact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contact.setBorder(null);
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 200, 28));

        jLabel45.setBackground(new java.awt.Color(0, 0, 0));
        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(74, 74, 74));
        jLabel45.setText("Contact Number     :");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 130, 20));

        Back.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 800, 580));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(102, 102, 102));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("All Rights Reserved © Kochi lnc. 2018");
        Back.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 180, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation( x - xx , y - xy );
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        try{
            conn = DatabaseConnection.ConnectDB();
            if(id.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Please Enter ID and Try Again","Error!!!" , 2 );
            }
            else{
                String Tac = "select * from WorkerAccademicInfo where Worker_Id = '"+id.getText()+"'";
                pst = conn.prepareStatement(Tac);
                rs = pst.executeQuery();
                if( rs.next() ){
                    teacherid.setText( rs.getString("Worker_Id"));
                    teachername.setText( rs.getString("Worker_Name"));

                    String rid = rs.getString("Rank_Id");
                    int rrid = Integer.parseInt(rid);
                    String q = "select Rank_Name from Designation where Rank_Id = "+rrid+"";
                    PreparedStatement pst2 = conn.prepareStatement(q);
                    ResultSet rs2 = pst2.executeQuery();
                    if( rs2.next() ){
                        rank.setText( rs2.getString("Rank_Name"));
                    }

                    tspeciality.setText( rs.getString("ExtraOrdinary"));
                    dateofjoin.setText( rs.getString("DateOfJoin"));
                }
                else{
                    JOptionPane.showMessageDialog(null,"No Worker Found!!\nPlease Enter a Valid ID","Error!!!" , 2 );
                }

                String Tperin = "Select * from WorkerPersonalInfo where Worker_Id = '"+id.getText()+"'";
                pst = conn.prepareStatement(Tperin);
                rs = pst.executeQuery();
                if( rs.next() ){
                    tfathername.setText( rs.getString("Fathers_Name"));
                    fatherphnno.setText( rs.getString("Father_Phone_Number"));
                    tmothername.setText( rs.getString("Mother_Name"));
                    motherphnno.setText( rs.getString("Mother_Phone_Number"));
                    tage.setText( rs.getString("Age"));
                    treligion.setText( rs.getString("Religion"));
                    tsex.setText( rs.getString("Sex"));
                    tnationality.setText(rs.getString("Nationality"));
                    contact.setText(rs.getString("Contact_No"));
                }
                String Tpread = "Select * from WorkerPresentAddress where Worker_Id = '"+id.getText()+"'";
                pst = conn.prepareStatement(Tpread);
                rs = pst.executeQuery();
                if( rs.next() ){
                    pre_house.setText(rs.getString("HouseNo_Road"));
                    pre_village.setText(rs.getString("Village"));
                    pre_town.setText(rs.getString("PostOffice"));
                    pre_postcode.setText(rs.getString("PostalCode"));
                    pre_district.setText(rs.getString("District"));
                    pre_subdistrict.setText(rs.getString("SubDistrict"));
                    pre_division.setText(rs.getString("Division"));
                    pre_country.setText(rs.getString("Country"));
                }
                String Tparad = "Select * from WorkerParmanentAddress where Worker_Id = '"+id.getText()+"'";
                pst = conn.prepareStatement(Tparad);
                rs = pst.executeQuery();
                if( rs.next() ){
                    par_house.setText(rs.getString("HouseNo_Road"));
                    par_village.setText(rs.getString("Village"));
                    par_town.setText(rs.getString("PostOffice"));
                    par_postcode.setText(rs.getString("PostalCode"));
                    par_district.setText(rs.getString("District"));
                    par_subdistrict.setText(rs.getString("SubDistrict"));
                    par_division.setText(rs.getString("Division"));
                    par_country.setText(rs.getString("Country"));
                }
            }
        }catch(Exception e ){JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_showMouseClicked

    private void showMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMousePressed
        show.setBackground(new java.awt.Color(0,122,244));
    }//GEN-LAST:event_showMousePressed

    private void showMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseReleased
        show.setBackground(new java.awt.Color(51,153,255));
    }//GEN-LAST:event_showMouseReleased

    private void resetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMousePressed
        reset.setBackground(new java.awt.Color(204,40,0));
    }//GEN-LAST:event_resetMousePressed

    private void resetMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseReleased
        reset.setBackground(new java.awt.Color(255,51,0 ));
    }//GEN-LAST:event_resetMouseReleased

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMousePressed
        minimize.setBackground(new java.awt.Color(0,123,123));
    }//GEN-LAST:event_minimizeMousePressed

    private void minimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseReleased
        minimize.setBackground(new java.awt.Color(0,153,153));
    }//GEN-LAST:event_minimizeMouseReleased

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        dispose();
        DashBoard back = new DashBoard();
        back.setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        back.setBackground(new java.awt.Color(0,123,123));
    }//GEN-LAST:event_backMousePressed

    private void backMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseReleased
        back.setBackground(new java.awt.Color(0,153,153));
    }//GEN-LAST:event_backMouseReleased

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        close.setBackground(new java.awt.Color(0,123,123));

        System.exit(0);
    }//GEN-LAST:event_closeMousePressed

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        close.setBackground(new java.awt.Color(0,153,153));
    }//GEN-LAST:event_closeMouseReleased

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx , y - xy );
    }//GEN-LAST:event_jPanel5MouseDragged

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Worker_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Worker_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Worker_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Worker_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Worker_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Back;
    private javax.swing.JPanel Shadow;
    private javax.swing.JLabel back;
    private javax.swing.JLabel close;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField dateofjoin;
    private javax.swing.JTextField fatherphnno;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel minimize;
    private javax.swing.JTextField motherphnno;
    private javax.swing.JTextField par_country;
    private javax.swing.JTextField par_district;
    private javax.swing.JTextField par_division;
    private javax.swing.JTextField par_house;
    private javax.swing.JTextField par_postcode;
    private javax.swing.JTextField par_subdistrict;
    private javax.swing.JTextField par_town;
    private javax.swing.JTextField par_village;
    private javax.swing.JTextField pre_country;
    private javax.swing.JTextField pre_district;
    private javax.swing.JTextField pre_division;
    private javax.swing.JTextField pre_house;
    private javax.swing.JTextField pre_postcode;
    private javax.swing.JTextField pre_subdistrict;
    private javax.swing.JTextField pre_town;
    private javax.swing.JTextField pre_village;
    private javax.swing.JTextField rank;
    private javax.swing.JLabel reset;
    private javax.swing.JLabel show;
    private javax.swing.JTextField tage;
    private javax.swing.JTextField teacherid;
    private javax.swing.JTextField teachername;
    private javax.swing.JTextField tfathername;
    private javax.swing.JTextField tmothername;
    private javax.swing.JTextField tnationality;
    private javax.swing.JTextField treligion;
    private javax.swing.JTextField tsex;
    private javax.swing.JTextField tspeciality;
    // End of variables declaration//GEN-END:variables
}
